import express from 'express';
import { timingSafeEqual } from 'node:crypto';
import { all, one, type Database } from './db.js';
import { insert } from './seed.js';
import { ApiError, date, number, required, choice, digest, sessionToken } from './security.js';
import { wrap, permit, mutate, audit, uid, versioned, type Req, type RouteContext } from './context.js';
import { calculatePayroll, validateMonth } from './payroll.js';

function employeeProjection(r:Req,row:any){if(r.user.permissions.includes('payroll.read'))return row;const rest={...row};for(const field of ['monthly_salary','absence_deduction','overtime_hour_rate','salary_transfer_method','salary_transfer_number','fixed_allowance','transport_allowance','meal_allowance','fixed_incentive','night_shift_rate','fixed_deduction'])delete rest[field];return rest}
function periodProjection(row:any){return {...row,...row.calculation,calculation:undefined}}
async function markChanged(db:Database,month?:string){await db.query(`UPDATE payroll_periods SET stale=true,version=version+1 WHERE status='draft'${month?' AND month=$1':''}`,month?[month]:[]);if(month)await db.query("UPDATE payroll_periods SET has_late_changes=true WHERE status='approved' AND month=$1",[month])}
async function assertUnlocked(db:Database,month:string){if(await one(db,"SELECT id FROM payroll_periods WHERE month=$1 AND status='approved'",[month]))throw new ApiError(409,'فترة الرواتب معتمدة ومقفلة؛ لا يمكن تعديل بياناتها','PAYROLL_LOCKED')}
function calendarDate(value:any){const str=required(value,'تاريخ النوبة');if(!/^\d{4}-\d{2}-\d{2}$/.test(str)||!Number.isFinite(new Date(str+'T00:00:00Z').getTime())||new Date(str+'T00:00:00Z').toISOString().slice(0,10)!==str)throw new ApiError(400,'تاريخ النوبة غير صالح');return str}
function clockTime(value:any){const str=required(value,'وقت النوبة');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(str))throw new ApiError(400,'الوقت يجب أن يكون بالصيغة HH:mm');return str}
async function toInstant(db:Database,value:any){const str=required(value,'وقت البصمة');if(/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}(:\d{2})?$/.test(str)){const row=await one(db,"SELECT $1::timestamp AT TIME ZONE 'Africa/Cairo' AS instant",[str]);return new Date(row.instant).toISOString()}if(!/[zZ]|[+-]\d\d:\d\d$/.test(str))throw new ApiError(400,'وقت البصمة يحتاج تاريخًا صحيحًا وتوقيت القاهرة أو فرق UTC صريح');return date(str,'البصمة')}
async function monthFor(db:Database,instant:string){return (await one(db,"SELECT to_char($1::timestamptz AT TIME ZONE 'Africa/Cairo','YYYY-MM') AS month",[instant])).month}
async function punchMonths(db:Database,instant:string,employeeId?:string){
 const months=new Set<string>([await monthFor(db,instant)]);
 if(employeeId){const shifts=await all(db,"SELECT DISTINCT to_char(shift_date,'YYYY-MM') AS month FROM attendance_shifts WHERE employee_id=$1 AND $2::timestamptz BETWEEN starts_at-interval '4 hours' AND ends_at+interval '8 hours'",[employeeId,instant]);for(const shift of shifts)months.add(shift.month)}
 return [...months];
}
async function addPunch(db:Database,body:any,source:string,actorId:string|null,device?:any){const occurred=await toInstant(db,body.occurred_at);if(new Date(occurred).getTime()>Date.now()+300000)throw new ApiError(400,'وقت البصمة في المستقبل؛ تحقق من ساعة الجهاز');let employee:any;if(body.employee_id)employee=await one(db,'SELECT * FROM hr_employees WHERE id=$1',[body.employee_id]);else if(body.device_pin)employee=await one(db,'SELECT * FROM hr_employees WHERE device_pin=$1',[String(body.device_pin)]);if(body.employee_id&&!employee)throw new ApiError(404,'الموظف غير موجود');if(source==='manual')for(const month of await punchMonths(db,occurred,employee?.id))await assertUnlocked(db,month);const pin=employee?.device_pin||required(String(body.device_pin||''),'رقم المستخدم على جهاز البصمة');const event=choice(body.event,['in','out','unknown'],'نوع البصمة');const source_key=digest(`${pin}|${occurred}|${event}`);const existing=await one(db,'SELECT * FROM attendance_punches WHERE source_key=$1',[source_key]);if(existing)return {punch:existing,inserted:false};const result=await one(db,'INSERT INTO attendance_punches(id,employee_id,device_id,device_pin,occurred_at,event,source,reason,source_key,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT DO NOTHING RETURNING *',[uid(),employee?.id||null,device?.id||null,pin,occurred,event,source,body.reason||null,source_key,actorId]);if(!result)return {punch:await one(db,'SELECT * FROM attendance_punches WHERE source_key=$1',[source_key]),inserted:false};for(const month of await punchMonths(db,occurred,employee?.id))await markChanged(db,month);return {punch:result,inserted:true}}
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell.trim());cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=ch}if(quoted)throw new ApiError(400,'علامات اقتباس CSV غير مكتملة');row.push(cell.trim());if(row.some(Boolean))rows.push(row);const headers=rows.shift()?.map(x=>x.replace(/^\uFEFF/,'').toLowerCase())||[];for(const field of ['device_pin','occurred_at','event'])if(!headers.includes(field))throw new ApiError(400,'يجب أن يحتوي CSV على device_pin,occurred_at,event');return rows.map((r,i)=>{if(r.length!==headers.length)throw new ApiError(400,`عدد أعمدة CSV غير صحيح في السطر ${i+2}`);return Object.fromEntries(headers.map((h,j)=>[h,r[j]]))})}
function validatePolicy(body:any){const fields:Record<string,number>={};const rules:Record<string,[number,number]>={grace_minutes:[0,120],paid_break_minutes:[0,240],working_days_per_month:[1,31],working_hours_per_day:[1,24],late_multiplier:[0,10],absence_multiplier:[0,10],overtime_multiplier:[0,10]};for(const [key,[min,max]]of Object.entries(rules))if(body[key]!==undefined)fields[key]=number(body[key],key,min,max);if(!Object.keys(fields).length)throw new ApiError(400,'أدخل إعدادًا واحدًا على الأقل');return fields}
function optionalText(value:any,label:string,max=500){if(value===undefined||value===null||value==='')return null;const result=required(value,label);if(result.length>max)throw new ApiError(400,`${label} أطول من الحد المسموح`);return result}
function employeeProfile(body:any){return {
 job_type:choice(body.job_type||'other',['doctor','nurse','reception','accountant','purchasing','technician','worker','administration','other'],'نوع الموظف'),
 job_title:optionalText(body.job_title,'المسمى الوظيفي',160),
 department:required(body.department||'حضّانات حديثي الولادة','القسم'),
 phone:optionalText(body.phone,'رقم الهاتف',40),
 whatsapp_phone:optionalText(body.whatsapp_phone,'رقم واتساب',40),
 hire_date:body.hire_date?date(body.hire_date,'تاريخ التعيين').slice(0,10):null,
};}
function payrollProfile(body:any){return {
 monthly_salary:body.monthly_salary!==undefined&&body.monthly_salary!==''?number(body.monthly_salary,'الراتب الأساسي',0):null,
 daily_work_hours:number(body.daily_work_hours??8,'ساعات العمل اليومية',1,16),
 work_days_per_month:Math.round(number(body.work_days_per_month??30,'أيام العمل الشهرية',1,31)),
 absence_deduction:body.absence_deduction!==undefined&&body.absence_deduction!==''?number(body.absence_deduction,'خصم يوم الغياب',0):null,
 overtime_hour_rate:body.overtime_hour_rate!==undefined&&body.overtime_hour_rate!==''?number(body.overtime_hour_rate,'سعر ساعة الإضافي',0):null,
 fixed_allowance:number(body.fixed_allowance??0,'البدل الثابت',0),
 transport_allowance:number(body.transport_allowance??0,'بدل الانتقال',0),
 meal_allowance:number(body.meal_allowance??0,'بدل الوجبات',0),
 fixed_incentive:number(body.fixed_incentive??0,'الحافز الثابت',0),
 night_shift_rate:number(body.night_shift_rate??0,'بدل السهرة',0),
 fixed_deduction:number(body.fixed_deduction??0,'الخصم الثابت',0),
 salary_transfer_method:body.salary_transfer_method?choice(body.salary_transfer_method,['cash','bank','wallet','instapay'],'طريقة تحويل الراتب'):null,
 salary_transfer_number:optionalText(body.salary_transfer_number,'رقم تحويل الراتب',160),
};}

export function attendanceRoutes({app,db}:RouteContext){
 app.get('/api/attendance',wrap(async(r,s)=>{const whole=r.user.permissions.includes('attendance.read');if(!whole)permit(r,'attendance.self');const employee=whole?null:await one(db,'SELECT id FROM hr_employees WHERE user_id=$1',[r.user.id]);const employeeId=whole?null:employee?.id||'none';const employees=await all(db,'SELECT * FROM hr_employees'+(whole?'':' WHERE id=$1')+' ORDER BY name',whole?[]:[employeeId]);const shifts=await all(db,`SELECT s.*,e.name AS employee_name,e.employee_no FROM attendance_shifts s JOIN hr_employees e ON e.id=s.employee_id${whole?'':' WHERE s.employee_id=$1'} ORDER BY s.starts_at DESC LIMIT 1000`,whole?[]:[employeeId]);const punches=await all(db,`SELECT p.*,e.name AS employee_name,d.name AS device_name FROM attendance_punches p LEFT JOIN hr_employees e ON e.id=p.employee_id LEFT JOIN attendance_devices d ON d.id=p.device_id${whole?'':' WHERE p.employee_id=$1'} ORDER BY p.occurred_at DESC LIMIT 1000`,whole?[]:[employeeId]);const handovers=await all(db,`SELECT h.*,s.shift_date,s.starts_at,s.ends_at,f.name AS from_employee_name,t.name AS to_employee_name,t.user_id AS to_user_id,u.name AS handed_over_by_name,ack.name AS acknowledged_by_name FROM attendance_shift_handovers h JOIN attendance_shifts s ON s.id=h.shift_id JOIN hr_employees f ON f.id=h.from_employee_id JOIN hr_employees t ON t.id=h.to_employee_id JOIN users u ON u.id=h.handed_over_by LEFT JOIN users ack ON ack.id=h.acknowledged_by${whole?'':' WHERE h.from_employee_id=$1 OR h.to_employee_id=$1'} ORDER BY h.handed_over_at DESC LIMIT 500`,whole?[]:[employeeId]);for(const handover of handovers)handover.can_acknowledge=handover.status==='pending'&&handover.to_user_id===r.user.id;const policy=await one(db,"SELECT * FROM attendance_policy WHERE id='default'");if(!r.user.permissions.includes('payroll.read'))policy.data={grace_minutes:policy.data.grace_minutes};const devices=whole?await all(db,'SELECT id,name,serial,timezone,active,last_seen_at,version FROM attendance_devices ORDER BY name'):[];const periods=r.user.permissions.includes('payroll.read')?(await all(db,'SELECT * FROM payroll_periods ORDER BY month DESC')).map(periodProjection):[];await audit(db,r,'read','attendance');s.json({employees:employees.map(e=>employeeProjection(r,e)),devices,shifts,punches,handovers,policy:{...policy.data,version:policy.version},periods,integration:{protocol:'ZKTeco ADMS ATTLOG subset',hardware_verified:false,authentication:'X-Device-Secret header or authenticated local gateway',endpoint:'/iclock/cdata?SN=DEVICE_SERIAL&table=ATTLOG',stores_biometrics:false}})}));
 app.post('/api/attendance/employees',wrap(async(r,s)=>{permit(r,'attendance.write');const hasPayroll=['monthly_salary','daily_work_hours','work_days_per_month','absence_deduction','overtime_hour_rate','fixed_allowance','transport_allowance','meal_allowance','fixed_incentive','night_shift_rate','fixed_deduction','salary_transfer_method','salary_transfer_number'].some(field=>r.body[field]!==undefined&&r.body[field]!=='');if(hasPayroll)permit(r,'payroll.write');s.status(201).json(await mutate(db,r,'hr_employees',async tx=>{const row=await insert(tx,'hr_employees',{id:uid(),name:required(r.body.name,'اسم الموظف'),employee_no:required(r.body.employee_no,'الرقم الوظيفي'),device_pin:required(String(r.body.device_pin||''),'رقم جهاز البصمة'),user_id:r.body.user_id||null,...employeeProfile(r.body),notes:optionalText(r.body.notes,'ملاحظات الموظف',2000),...(hasPayroll?payrollProfile(r.body):{})});await tx.query('UPDATE attendance_punches SET employee_id=$1 WHERE device_pin=$2 AND employee_id IS NULL',[row.id,row.device_pin]);await markChanged(tx);return employeeProjection(r,row)}))}));
 app.patch('/api/attendance/employees/:id',wrap(async(r,s)=>{if(!r.user.permissions.includes('attendance.write'))permit(r,'payroll.write');s.json(await mutate(db,r,'hr_employees',async tx=>{const current=await one(tx,'SELECT * FROM hr_employees WHERE id=$1',[r.params.id]);if(!current)throw new ApiError(404,'الموظف غير موجود');const fields:Record<string,any>={};for(const field of ['name','employee_no','device_pin'])if(r.body[field]!==undefined){permit(r,'attendance.write');fields[field]=required(String(r.body[field]),field)}if(['job_type','job_title','department','phone','whatsapp_phone','hire_date'].some(field=>r.body[field]!==undefined)){permit(r,'attendance.write');Object.assign(fields,employeeProfile({...current,...r.body}))}if(r.body.notes!==undefined){permit(r,'attendance.write');fields.notes=optionalText(r.body.notes,'ملاحظات الموظف',2000)}if(r.body.user_id!==undefined){permit(r,'attendance.write');fields.user_id=r.body.user_id||null}if(r.body.active!==undefined){permit(r,'attendance.write');if(typeof r.body.active!=='boolean')throw new ApiError(400,'حالة الموظف غير صالحة');fields.active=r.body.active}const payrollFields=['monthly_salary','daily_work_hours','work_days_per_month','absence_deduction','overtime_hour_rate','fixed_allowance','transport_allowance','meal_allowance','fixed_incentive','night_shift_rate','fixed_deduction','salary_transfer_method','salary_transfer_number'];if(payrollFields.some(field=>r.body[field]!==undefined)){permit(r,'payroll.write');Object.assign(fields,payrollProfile({...current,...r.body}))}if(!Object.keys(fields).length)throw new ApiError(400,'لا توجد بيانات للتعديل');const updated=await versioned(tx,'hr_employees',current.id,r.body.version,fields);await tx.query('UPDATE attendance_punches SET employee_id=$1 WHERE device_pin=$2 AND employee_id IS NULL',[current.id,updated.device_pin]);await markChanged(tx);return employeeProjection(r,updated)}))}));
 app.post('/api/attendance/devices',wrap(async(r,s)=>{permit(r,'attendance.devices');const secret=sessionToken();const device=await db.transaction(async tx=>{const created=await insert(tx,'attendance_devices',{id:uid(),name:required(r.body.name,'اسم الجهاز'),serial:required(r.body.serial,'الرقم التسلسلي'),secret_hash:digest(secret),timezone:'Africa/Cairo'});await audit(tx,r,'create','attendance_devices',created.id);return created});const {secret_hash,...safe}=device;s.status(201).json({device:safe,secret})}));
 app.patch('/api/attendance/devices/:id',wrap(async(r,s)=>{permit(r,'attendance.devices');s.json(await mutate(db,r,'attendance_devices',async tx=>{const fields:Record<string,any>={};if(r.body.active!==undefined){if(typeof r.body.active!=='boolean')throw new ApiError(400,'حالة الجهاز غير صالحة');fields.active=r.body.active}if(r.body.name!==undefined)fields.name=required(r.body.name,'اسم الجهاز');if(!Object.keys(fields).length)throw new ApiError(400,'لا توجد بيانات للتعديل');const {secret_hash,...row}=await versioned(tx,'attendance_devices',String(r.params.id),r.body.version,fields);return row}))}));
 app.post('/api/attendance/devices/:id/rotate-secret',wrap(async(r,s)=>{permit(r,'attendance.devices');const secret=sessionToken();await db.transaction(async tx=>{const row=await one(tx,'UPDATE attendance_devices SET secret_hash=$1,version=version+1 WHERE id=$2 RETURNING id',[digest(secret),r.params.id]);if(!row)throw new ApiError(404,'الجهاز غير موجود');await audit(tx,r,'rotate_secret','attendance_devices',row.id);return row});s.json({secret})}));
 app.post('/api/attendance/shifts',wrap(async(r,s)=>{permit(r,'attendance.write');s.status(201).json(await mutate(db,r,'attendance_shifts',async tx=>{const shiftDate=calendarDate(r.body.shift_date),start=clockTime(r.body.start_time),end=clockTime(r.body.end_time);if(start===end)throw new ApiError(400,'بداية النوبة ونهايتها لا يمكن أن تتساويا');await assertUnlocked(tx,shiftDate.slice(0,7));const employee=await one(tx,'SELECT id FROM hr_employees WHERE id=$1 AND active=true FOR UPDATE',[r.body.employee_id]);if(!employee)throw new ApiError(404,'الموظف غير موجود أو غير نشط');const times=await one(tx,"SELECT ($1::date+$2::time) AT TIME ZONE 'Africa/Cairo' AS starts_at,($1::date+$3::time+CASE WHEN $3::time<$2::time THEN interval '1 day' ELSE interval '0 days' END) AT TIME ZONE 'Africa/Cairo' AS ends_at",[shiftDate,start,end]);if(new Date(times.ends_at).getTime()-new Date(times.starts_at).getTime()>16*3600000)throw new ApiError(400,'النوبة تتجاوز 16 ساعة؛ قسّم الجدول وراجعه');if(await one(tx,'SELECT id FROM attendance_shifts WHERE employee_id=$1 AND starts_at<$2 AND ends_at>$3',[employee.id,times.ends_at,times.starts_at]))throw new ApiError(409,'توجد نوبة متداخلة للموظف');const row=await insert(tx,'attendance_shifts',{id:uid(),employee_id:employee.id,shift_date:shiftDate,...times,created_by:r.user.id});await markChanged(tx,shiftDate.slice(0,7));return row}))}));
 app.post('/api/attendance/handovers',wrap(async(r,s)=>{const manages=r.user.permissions.includes('attendance.write');if(!manages)permit(r,'attendance.self');s.status(201).json(await mutate(db,r,'attendance_shift_handovers',async tx=>{const shift=await one(tx,'SELECT s.*,e.name AS employee_name,e.user_id AS employee_user_id FROM attendance_shifts s JOIN hr_employees e ON e.id=s.employee_id WHERE s.id=$1 FOR UPDATE',[required(r.body.shift_id,'النوبة المسلّمة')]);if(!shift)throw new ApiError(404,'النوبة غير موجودة');if(!manages&&shift.employee_user_id!==r.user.id)throw new ApiError(403,'الموظف لا يستطيع تسليم شيفت موظف آخر');if(await one(tx,'SELECT id FROM attendance_shift_handovers WHERE shift_id=$1',[shift.id]))throw new ApiError(409,'تم تسجيل تسليم لهذه النوبة بالفعل');const recipient=await one(tx,'SELECT id,user_id FROM hr_employees WHERE id=$1 AND active=true',[required(r.body.to_employee_id,'الموظف المستلم')]);if(!recipient)throw new ApiError(404,'الموظف المستلم غير موجود أو غير نشط');if(recipient.id===shift.employee_id)throw new ApiError(400,'المسلّم والمستلم لا يمكن أن يكونا نفس الموظف');return insert(tx,'attendance_shift_handovers',{id:uid(),shift_id:shift.id,from_employee_id:shift.employee_id,to_employee_id:recipient.id,summary:required(r.body.summary,'ملخص تسليم الشيفت'),handed_over_by:r.user.id})}))}));
 app.post('/api/attendance/handovers/:id/acknowledge',wrap(async(r,s)=>{s.json(await mutate(db,r,'attendance_shift_handovers',async tx=>{const handover=await one(tx,'SELECT h.*,e.user_id AS recipient_user_id FROM attendance_shift_handovers h JOIN hr_employees e ON e.id=h.to_employee_id WHERE h.id=$1 FOR UPDATE',[r.params.id]);if(!handover)throw new ApiError(404,'تسليم الشيفت غير موجود');if(handover.recipient_user_id!==r.user.id)throw new ApiError(403,'الموظف المستلم فقط يؤكد استلام الشيفت بحسابه');if(handover.status!=='pending')throw new ApiError(409,'تم تأكيد استلام الشيفت بالفعل');return versioned(tx,'attendance_shift_handovers',handover.id,r.body.version,{status:'acknowledged',acknowledged_by:r.user.id,acknowledged_at:new Date().toISOString()})}))}));
 app.post('/api/attendance/punches',wrap(async(r,s)=>{permit(r,'attendance.write');required(r.body.reason,'سبب الإدخال اليدوي');s.status(201).json(await mutate(db,r,'attendance_punches',async tx=>{const instant=await toInstant(tx,r.body.occurred_at);await assertUnlocked(tx,await monthFor(tx,instant));const device=r.body.device_id?await one(tx,'SELECT * FROM attendance_devices WHERE id=$1',[r.body.device_id]):undefined;if(r.body.device_id&&!device)throw new ApiError(404,'الجهاز غير موجود');const result=await addPunch(tx,r.body,'manual',r.user.id,device);return {...result.punch,duplicate:!result.inserted}}))}));
 app.post('/api/attendance/punches/:id/void',wrap(async(r,s)=>{permit(r,'attendance.write');s.json(await mutate(db,r,'attendance_punches',async tx=>{const p=await one(tx,'SELECT * FROM attendance_punches WHERE id=$1',[r.params.id]);if(!p)throw new ApiError(404,'البصمة غير موجودة');const months=await punchMonths(tx,p.occurred_at,p.employee_id);for(const month of months)await assertUnlocked(tx,month);const row=await versioned(tx,'attendance_punches',p.id,r.body.version,{voided:true,void_reason:required(r.body.reason,'سبب إلغاء البصمة'),voided_by:r.user.id});for(const month of months)await markChanged(tx,month);return row}))}));
 app.post('/api/attendance/import',wrap(async(r,s)=>{permit(r,'attendance.write');const rows=parseCsv(required(r.body.csv,'محتوى CSV'));if(!rows.length||rows.length>5000)throw new ApiError(400,'يسمح باستيراد من 1 إلى 5000 بصمة في المرة');s.status(201).json(await mutate(db,r,'attendance_imports',async tx=>{const device=r.body.device_id?await one(tx,'SELECT * FROM attendance_devices WHERE id=$1',[r.body.device_id]):undefined;if(r.body.device_id&&!device)throw new ApiError(404,'الجهاز غير موجود');let count=0;for(const row of rows){const result=await addPunch(tx,row,'csv',r.user.id,device);if(result.inserted)count++}return insert(tx,'attendance_imports',{id:uid(),device_id:device?.id||null,source:'csv',received_count:rows.length,inserted_count:count,actor_id:r.user.id})}))}));
 app.patch('/api/attendance/policy',wrap(async(r,s)=>{permit(r,'payroll.write');s.json(await mutate(db,r,'attendance_policy',async tx=>{const current=await one(tx,"SELECT * FROM attendance_policy WHERE id='default'");const data={...current.data,...validatePolicy(r.body)};const result=await versioned(tx,'attendance_policy','default',r.body.version,{data:JSON.stringify(data)});await markChanged(tx);return {...result.data,version:result.version}}))}));
 app.post('/api/payroll/adjustments',wrap(async(r,s)=>{permit(r,'payroll.write');const month=validateMonth(r.body.month);await assertUnlocked(db,month);s.status(201).json(await mutate(db,r,'payroll_adjustments',async tx=>{const employee=await one(tx,'SELECT id FROM hr_employees WHERE id=$1 AND active=true',[r.body.employee_id]);if(!employee)throw new ApiError(404,'الموظف غير موجود أو غير نشط');const row=await insert(tx,'payroll_adjustments',{id:uid(),employee_id:employee.id,month,type:choice(r.body.type,['allowance','incentive','bonus','night_shift','deduction','advance','other_addition','other_deduction'],'نوع تسوية الراتب'),amount:number(r.body.amount,'قيمة تسوية الراتب',0.01,1000000000),notes:required(r.body.notes,'سبب تسوية الراتب'),actor_id:r.user.id});await markChanged(tx,month);return row}))}));
 app.post('/api/payroll/adjustments/:id/void',wrap(async(r,s)=>{permit(r,'payroll.write');s.json(await mutate(db,r,'payroll_adjustments',async tx=>{const row=await one(tx,'SELECT * FROM payroll_adjustments WHERE id=$1 FOR UPDATE',[r.params.id]);if(!row||row.voided)throw new ApiError(404,'تسوية الراتب غير موجودة');await assertUnlocked(tx,row.month);await tx.query('UPDATE payroll_adjustments SET voided=true,voided_by=$1,voided_at=now(),void_reason=$2 WHERE id=$3',[r.user.id,required(r.body.reason,'سبب إلغاء التسوية'),row.id]);await markChanged(tx,row.month);return{...row,voided:true}}))}));
 app.post('/api/payroll/preview',wrap(async(r,s)=>{permit(r,'payroll.read');permit(r,'payroll.write');const month=validateMonth(r.body.month);s.status(201).json(await mutate(db,r,'payroll_periods',async tx=>{const existing=await one(tx,'SELECT * FROM payroll_periods WHERE month=$1',[month]);if(existing)return periodProjection(existing);const calculation=await calculatePayroll(tx,month);return periodProjection(await insert(tx,'payroll_periods',{id:uid(),month,calculation:JSON.stringify(calculation),created_by:r.user.id}))}))}));
 app.get('/api/payroll/:id',wrap(async(r,s)=>{permit(r,'payroll.read');const row=await one(db,'SELECT * FROM payroll_periods WHERE id=$1',[r.params.id]);if(!row)throw new ApiError(404,'فترة الرواتب غير موجودة');s.json(periodProjection(row))}));
 app.post('/api/payroll/:id/recalculate',wrap(async(r,s)=>{permit(r,'payroll.read');permit(r,'payroll.write');s.json(await mutate(db,r,'payroll_periods',async tx=>{const row=await one(tx,'SELECT * FROM payroll_periods WHERE id=$1 FOR UPDATE',[r.params.id]);if(!row)throw new ApiError(404,'فترة الرواتب غير موجودة');if(row.status==='approved')throw new ApiError(409,'فترة الرواتب معتمدة ومقفلة','PAYROLL_LOCKED');const calculation=await calculatePayroll(tx,row.month);return periodProjection(await versioned(tx,'payroll_periods',row.id,r.body.version,{calculation:JSON.stringify(calculation),stale:false,calculated_at:new Date().toISOString()}))}))}));
 app.post('/api/payroll/:id/approve',wrap(async(r,s)=>{permit(r,'payroll.read');permit(r,'payroll.approve');s.json(await mutate(db,r,'payroll_periods',async tx=>{const row=await one(tx,'SELECT * FROM payroll_periods WHERE id=$1 FOR UPDATE',[r.params.id]);if(!row)throw new ApiError(404,'فترة الرواتب غير موجودة');if(row.status==='approved')throw new ApiError(409,'فترة الرواتب معتمدة بالفعل','PAYROLL_LOCKED');if(row.stale)throw new ApiError(409,'تغيرت بيانات الحضور أو القواعد؛ أعد الحساب ثم راجع الكشف','PAYROLL_STALE');if(row.calculation.issues.length)throw new ApiError(409,'توجد بصمات أو بيانات ناقصة؛ صحح المشكلات وأعد الحساب قبل الاعتماد','PAYROLL_ISSUES');const periodEnd=new Date(`${row.month}-01T00:00:00Z`);periodEnd.setUTCMonth(periodEnd.getUTCMonth()+1);if(periodEnd.getTime()>Date.now())throw new ApiError(409,'لا يمكن اعتماد رواتب شهر لم ينتهِ بعد');return periodProjection(await versioned(tx,'payroll_periods',row.id,r.body.version,{status:'approved',approved_by:r.user.id,approved_at:new Date().toISOString()}))}))}));
}

export function attendanceDeviceRoutes({app,db}:RouteContext){
 async function deviceFor(r:Req){const serial=required(String(r.query.SN||''),'الرقم التسلسلي للجهاز');const secret=r.get('X-Device-Secret')||r.get('Authorization')?.replace(/^Bearer\s+/i,'')||'';const device=await one(db,'SELECT * FROM attendance_devices WHERE serial=$1 AND active=true',[serial]);const actual=Buffer.from(digest(secret));const expected=Buffer.from(device?.secret_hash||digest('invalid'));if(!device||!secret||actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new ApiError(401,'توثيق جهاز البصمة غير صحيح');return device}
 app.get('/iclock/cdata',wrap(async(r,s)=>{const device=await deviceFor(r);await db.query('UPDATE attendance_devices SET last_seen_at=now() WHERE id=$1',[device.id]);s.type('text/plain').send(`GET OPTION FROM: ${device.serial}\nATTLOGStamp=0\nOpStamp=0\nErrorDelay=60\nDelay=30\nTransTimes=00:00;14:05\nTransInterval=1\nTransFlag=1111000000\nRealtime=1\nEncrypt=0\n`) }));
 app.get('/iclock/getrequest',wrap(async(r,s)=>{await deviceFor(r);s.type('text/plain').send('OK')}));
 app.post('/iclock/cdata',express.text({type:'*/*',limit:'2mb'}),wrap(async(r,s)=>{const device=await deviceFor(r);if(r.query.table!=='ATTLOG')throw new ApiError(400,'هذا الموصل يقبل ATTLOG فقط؛ لا يخزن قوالب البصمات أو الصور');if(typeof r.body!=='string')throw new ApiError(400,'محتوى ATTLOG يجب أن يكون نصًا');const lines=r.body.split(/\r?\n/).filter((line:string)=>line.trim());if(lines.length>5000)throw new ApiError(400,'دفعة البصمات كبيرة جدًا');await db.transaction(async tx=>{let inserted=0;for(const line of lines){const fields=line.split('\t');if(fields.length<3)throw new ApiError(400,'سطر ATTLOG غير صالح');const event=fields[2]==='0'?'in':fields[2]==='1'?'out':'unknown';const result=await addPunch(tx,{device_pin:fields[0],occurred_at:fields[1],event},'zk_push',null,device);if(result.inserted)inserted++}await insert(tx,'attendance_imports',{id:uid(),device_id:device.id,source:'zk_push',received_count:lines.length,inserted_count:inserted});await tx.query('UPDATE attendance_devices SET last_seen_at=now() WHERE id=$1',[device.id]);await audit(tx,r,'device_import','attendance',device.id,{received:lines.length,inserted})});s.type('text/plain').send(`OK: ${lines.length}`)}));
}
