import { all, one } from "./db.js";
import { audit, permit, wrap, type Req, type RouteContext } from "./context.js";
import { ApiError } from "./security.js";
import { getLocale } from "./i18n.js";
import { accountingJournals } from "./accounting.js";

const n = (v: unknown) => Math.round(Number(v || 0) * 100) / 100;
const esc = (v: unknown) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);
function period(r: Req) {
  const end = String(r.query.end || new Date().toISOString().slice(0, 10));
  const from = String(r.query.from || `${end.slice(0,4)}-01-01`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(from) || !/^\d{4}-\d{2}-\d{2}$/.test(end) || from > end)
    throw new ApiError(400, "فترة التقرير المالي غير صالحة");
  return { from, end };
}
async function calculate(db: any, from: string, end: string) {
  const [periodEntries,cumulative,accounts]=await Promise.all([accountingJournals(db,from,end),accountingJournals(db,'1900-01-01',end),all(db,'SELECT * FROM chart_accounts WHERE active=true ORDER BY code')]);
  const sum=(entries:any[])=>{const map=new Map<string,{debit:number;credit:number}>();for(const journal of entries)for(const row of journal.lines){const x=map.get(row.account)||{debit:0,credit:0};x.debit=n(x.debit+Number(row.debit));x.credit=n(x.credit+Number(row.credit));map.set(row.account,x)}return map},periodMap=sum(periodEntries),cumulativeMap=sum(cumulative),key=(a:any)=>a.system_key||a.code,balance=(map:Map<string,any>,a:any)=>{const x=map.get(key(a))||{debit:0,credit:0};return a.type==='asset'||a.type==='expense'?n(x.debit-x.credit):n(x.credit-x.debit)};
  const revenueAccounts=accounts.filter((a:any)=>a.type==='revenue'),expenseAccounts=accounts.filter((a:any)=>a.type==='expense'),assetAccounts=accounts.filter((a:any)=>a.type==='asset'),liabilityAccounts=accounts.filter((a:any)=>a.type==='liability');
  const revenueTotal=n(revenueAccounts.reduce((s:number,a:any)=>s+balance(periodMap,a),0)),expenses=n(expenseAccounts.reduce((s:number,a:any)=>s+balance(periodMap,a),0)),netIncome=n(revenueTotal-expenses);
  const cash=balance(cumulativeMap,accounts.find((a:any)=>a.system_key==='money')),patientReceivables=balance(cumulativeMap,accounts.find((a:any)=>a.system_key==='patient_receivable')),insurance=balance(cumulativeMap,accounts.find((a:any)=>a.system_key==='insurance_receivable')),receivables=n(patientReceivables+insurance),inventory=balance(cumulativeMap,accounts.find((a:any)=>a.system_key==='inventory'));
  const assets=n(assetAccounts.reduce((s:number,a:any)=>s+balance(cumulativeMap,a),0)),liabilities=n(liabilityAccounts.reduce((s:number,a:any)=>s+balance(cumulativeMap,a),0)),equity=n(assets-liabilities);
  const income=[...revenueAccounts.map((a:any)=>({label:a.name_ar,label_en:a.name_en,amount:balance(periodMap,a)})),{label:'إجمالي الإيرادات',amount:revenueTotal,total:true},...expenseAccounts.map((a:any)=>({label:a.name_ar,label_en:a.name_en,amount:-balance(periodMap,a)})),{label:'صافي الدخل',amount:netIncome,total:true}];
  const position=[...assetAccounts.map((a:any)=>({label:a.name_ar,label_en:a.name_en,amount:balance(cumulativeMap,a)})),{label:'إجمالي الأصول',amount:assets,total:true},...liabilityAccounts.map((a:any)=>({label:a.name_ar,label_en:a.name_en,amount:balance(cumulativeMap,a)})),{label:'الالتزامات المسجلة',amount:liabilities,total:true},{label:'صافي حقوق الملكية / الأرصدة المتراكمة',amount:equity,total:true}];
  const cashChanges=periodEntries.map(j=>n(j.lines.filter(l=>l.account==='money').reduce((sum,l)=>sum+Number(l.debit)-Number(l.credit),0))),inflow=n(cashChanges.reduce((sum,change)=>sum+Math.max(change,0),0)),outflow=n(cashChanges.reduce((sum,change)=>sum+Math.max(-change,0),0));
  const flows=new Map<string,number>();for(const j of periodEntries){const amount=n(j.lines.filter((l:any)=>l.account==='money').reduce((s:number,l:any)=>s+Number(l.debit)-Number(l.credit),0));if(amount)flows.set(j.source,n((flows.get(j.source)||0)+amount))}
  const cashflow=[...Array.from(flows.entries(),([label,amount])=>({label:`تدفق - ${label}`,amount})),{label:'إجمالي التدفقات الداخلة',amount:inflow,total:true},{label:'إجمالي التدفقات الخارجة',amount:-outflow,total:true},{label:'صافي التدفق النقدي',amount:n(inflow-outflow),total:true}];
  const trial:any[]=accounts.map((a:any)=>{const x=periodMap.get(key(a))||{debit:0,credit:0};return{label:a.name_ar,label_en:a.name_en,debit:x.debit,credit:x.credit}}),debit=n(trial.reduce((s:number,x:any)=>s+x.debit,0)),credit=n(trial.reduce((s:number,x:any)=>s+x.credit,0));trial.push({label:'الإجمالي',debit,credit,total:true});
  const agingRows=await all(db,`SELECT CASE WHEN age_days<=30 THEN '0-30' WHEN age_days<=60 THEN '31-60' WHEN age_days<=90 THEN '61-90' ELSE '90+' END label,sum(balance) amount,count(*)::int count FROM (SELECT GREATEST(0,COALESCE((SELECT sum(amount) FROM charges c WHERE c.admission_id=a.id AND c.created_at < $1::date + interval '1 day'),0)-COALESCE((SELECT sum(amount) FROM payments p WHERE p.admission_id=a.id AND p.created_at < $1::date + interval '1 day'),0)) balance,($1::date-a.admitted_at::date) age_days FROM admissions a) q WHERE balance>0 GROUP BY 1 ORDER BY min(age_days)`,[end]);
  return {period:{from,end,currency:'EGP'},summary:{revenue:revenueTotal,expenses,net_income:netIncome,cash,receivables,assets,liabilities},income,position,cashflow,trial,aging:agingRows.map((x:any)=>({label:x.label,amount:n(x.amount),count:Number(x.count)})),notes:['كل الأرقام مترابطة مع دفتر الأستاذ الموحد ومصادرها التشغيلية الأصلية.','لا تظهر الأصول الثابتة أو الالتزامات غير المسجلة حتى يتم إدخالها في دليل الحسابات والقيود.']};
}
function excelXml(data:any){const sheets:Array<[string,any[],string[]]>=[["Summary",Object.entries(data.summary).map(([label,amount])=>({label,amount})),["label","amount"]],["Income",data.income,["label","amount"]],["Position",data.position,["label","amount"]],["Cash Flow",data.cashflow,["label","amount"]],["Trial Balance",data.trial,["label","debit","credit"]],["Aging",data.aging,["label","count","amount"]]];return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="h"><Font ss:Bold="1"/><Interior ss:Color="#DDEBF7" ss:Pattern="Solid"/></Style><Style ss:ID="n"><NumberFormat ss:Format="#,##0.00"/></Style></Styles>${sheets.map(([name,rows,cols])=>`<Worksheet ss:Name="${esc(name)}"><Table><Row>${cols.map((c:string)=>`<Cell ss:StyleID="h"><Data ss:Type="String">${esc(c)}</Data></Cell>`).join("")}</Row>${rows.map((r:any)=>`<Row>${cols.map((c:string)=>`<Cell${c==='label'?'':' ss:StyleID="n"'}><Data ss:Type="${c==='label'?'String':'Number'}">${esc(r[c]??0)}</Data></Cell>`).join("")}</Row>`).join("")}</Table></Worksheet>`).join("")}</Workbook>`}
const englishLabels:Record<string,string>={service:"Services",consumable:"Consumables",equipment:"Equipment","إجمالي الإيرادات":"Total revenue","مشتريات ومستلزمات":"Purchases and supplies","مصروفات الصيانة":"Maintenance expenses","صافي الدخل":"Net income","مديونيات المرضى":"Patient receivables","مستحقات شركات التأمين":"Insurance receivables","قيمة المخزون":"Inventory value","إجمالي الأصول":"Total assets","الالتزامات المسجلة":"Recorded liabilities","صافي حقوق الملكية / الأرصدة المتراكمة":"Net equity / accumulated balances","إجمالي التدفقات الداخلة":"Total cash inflows","إجمالي التدفقات الخارجة":"Total cash outflows","مدفوعات المشتريات":"Purchase payments","مدفوعات الصيانة":"Maintenance payments","صافي التدفق النقدي":"Net cash flow","النقدية والبنوك":"Cash and banks","المدينون":"Receivables","المخزون":"Inventory","المصروفات":"Expenses","إيرادات الخدمات":"Service revenue","رصيد افتتاحي وحقوق ملكية موازن":"Opening balance and balancing equity","الإجمالي":"Total"};
function localized(data:any,english:boolean){if(!english)return data;const sources:Record<string,string>={invoice:"patient invoices",payment:"patient collections",insurance:"insurance claims",treasury:"treasury transfers",purchase:"purchases",maintenance:"maintenance",payroll:"payroll",inventory:"inventory movements",opening:"opening balances",supplier_payment:"supplier payments",payroll_payment:"payroll payments",manual:"manual journals"};const translate=(x:any)=>x.label_en||x.label.startsWith("تدفق - ")?x.label_en||`Cash flow - ${sources[x.label.slice(7)]||x.label.slice(7)}`:englishLabels[x.label]||x.label;return {...data,income:data.income.map((x:any)=>({...x,label:translate(x)})),position:data.position.map((x:any)=>({...x,label:translate(x)})),cashflow:data.cashflow.map((x:any)=>({...x,label:translate(x)})),trial:data.trial.map((x:any)=>({...x,label:translate(x)})),notes:["All figures are linked to the unified general ledger and their original operational sources.","Fixed assets and unrecorded liabilities appear after they are entered in the chart of accounts and journals."]}}
function printHtml(data:any,english:boolean){const names=english?["Income statement","Financial position","Cash flows","Trial balance","Receivables aging"]:["قائمة الدخل","المركز المالي","التدفقات النقدية","ميزان المراجعة","أعمار المديونيات"];const sets=[data.income,data.position,data.cashflow,data.trial,data.aging];return `<!doctype html><html dir="${english?'ltr':'rtl'}"><head><meta charset="utf-8"><title>${english?'Financial statements':'القوائم المالية'}</title><style>body{font-family:Arial,sans-serif;color:#173e48;margin:28px}h1{color:#087f75}section{break-inside:avoid;margin:24px 0}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccdeda;padding:8px;text-align:start}th{background:#edf7f5}.num{text-align:end}@media print{@page{size:A4;margin:12mm}.toolbar{display:none}}</style></head><body><div class="toolbar"><button onclick="print()">${english?'Print / Save PDF':'طباعة / حفظ PDF'}</button></div><h1>${english?'Qasr Al Maadi Hospital — Financial statements':'مستشفى قصر المعادي — القوائم المالية'}</h1><p>${data.period.from} — ${data.period.end} · EGP</p>${sets.map((rows,i)=>`<section><h2>${names[i]}</h2><table><thead><tr><th>${english?'Item':'البيان'}</th><th>${english?'Debit / Amount':'مدين / قيمة'}</th><th>${english?'Credit':'دائن'}</th></tr></thead><tbody>${rows.map((r:any)=>`<tr><td>${esc(r.label)}</td><td class="num">${n(r.amount??r.debit).toLocaleString(english?'en-EG':'ar-EG',{minimumFractionDigits:2})}</td><td class="num">${r.credit===undefined?'':n(r.credit).toLocaleString(english?'en-EG':'ar-EG',{minimumFractionDigits:2})}</td></tr>`).join("")}</tbody></table></section>`).join("")}<small>${data.notes.map(esc).join(" · ")}</small></body></html>`}
export function financialStatementRoutes({app,db}:RouteContext){app.get('/api/financial-statements',wrap(async(r,s)=>{permit(r,'reports.read');const {from,end}=period(r),data=localized(await calculate(db,from,end),getLocale(r)==='en'),format=String(r.query.format||'json');await audit(db,r,format==='json'?'read':'export','financial-statements',undefined,{from,end,format});if(format==='excel'){s.setHeader('Content-Type','application/vnd.ms-excel; charset=utf-8');s.setHeader('Content-Disposition',`attachment; filename="financial-statements-${from}-${end}.xls"`);return s.send(excelXml(data))}if(format==='pdf')return s.type('html').send(printHtml(data,getLocale(r)==='en'));s.json(data)}));}




