import { all, one, type Database } from './db.js';
import { ApiError } from './security.js';
export const roundMoney=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export function validateMonth(value:unknown){if(typeof value!=='string'||!/^\d{4}-(0[1-9]|1[0-2])$/.test(value))throw new ApiError(400,'الشهر يجب أن يكون بالصيغة YYYY-MM');return value}
export function calculateEmployee(employee:any,shifts:any[],punches:any[],policy:any,adjustments:any[]=[]){
 const issues:{code:string;shift_id?:string;message:string}[]=[];
 const workingDays=Number(employee.work_days_per_month||policy.working_days_per_month);
 const workingHours=Number(employee.daily_work_hours||policy.working_hours_per_day);
 const salaryDayRate=Number(employee.monthly_salary||0)/workingDays;
 const absenceDayRate=employee.absence_deduction===null||employee.absence_deduction===undefined
  ? salaryDayRate*Number(policy.absence_multiplier)
  : Number(employee.absence_deduction);
 const hourRate=salaryDayRate/workingHours;
 const overtimeHourRate=employee.overtime_hour_rate===null||employee.overtime_hour_rate===undefined
  ? hourRate*Number(policy.overtime_multiplier)
  : Number(employee.overtime_hour_rate);
 if(employee.monthly_salary===null)issues.push({code:'MISSING_SALARY',message:'الراتب الأساسي غير محدد'});
 if(!shifts.length)issues.push({code:'MISSING_SCHEDULE',message:'لا توجد نوبات مجدولة للموظف في الفترة'});
 const assigned=new Map<string,any[]>();for(const sh of shifts)assigned.set(sh.id,[]);

 for(const punch of punches){const t=new Date(punch.occurred_at).getTime();const candidates=shifts.filter(sh=>t>=new Date(sh.starts_at).getTime()-4*3600000&&t<=new Date(sh.ends_at).getTime()+8*3600000);if(!candidates.length)continue;candidates.sort((a,b)=>{const anchor=(sh:any)=>new Date(punch.event==='out'?sh.ends_at:sh.starts_at).getTime();return Math.abs(t-anchor(a))-Math.abs(t-anchor(b))});assigned.get(candidates[0].id)!.push(punch)}
 const days=shifts.map(sh=>{const start=new Date(sh.starts_at).getTime(),end=new Date(sh.ends_at).getTime(),cairoHour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Cairo',hour:'2-digit',hourCycle:'h23'}).format(new Date(sh.starts_at)));const logs=assigned.get(sh.id)!.sort((a,b)=>new Date(a.occurred_at).getTime()-new Date(b.occurred_at).getTime());const row:any={shift_id:sh.id,shift_date:sh.shift_date,starts_at:sh.starts_at,ends_at:sh.ends_at,status:'present',night_shift:cairoHour>=18||cairoHour<6,first_in:null,last_out:null,worked_minutes:0,late_minutes:0,early_minutes:0,overtime_minutes:0,unpaid_break_minutes:0,absence_deduction:0,late_deduction:0,overtime_pay:0,punch_ids:logs.map(p=>p.id)};
  if(end>Date.now()){row.status=start>Date.now()?'upcoming':'in_progress';issues.push({code:'SHIFT_NOT_FINISHED',shift_id:sh.id,message:'النوبة لم تنتهِ بعد؛ لا يحتسب الغياب قبل انتهاء النوبة'});return row}
  if(!logs.length){row.status='absent';row.absence_deduction=roundMoney(absenceDayRate);return row}
  let open:any=null;let broken=false;let insideMinutes=0;let overtimeMinutes=0;for(const p of logs){if(p.event==='in'){if(open)broken=true;else open=p;if(!row.first_in)row.first_in=p.occurred_at}else if(p.event==='out'){if(!open)broken=true;else{const pairStart=new Date(open.occurred_at).getTime(),pairEnd=new Date(p.occurred_at).getTime();row.worked_minutes+=(pairEnd-pairStart)/60000;insideMinutes+=Math.max(0,Math.min(pairEnd,end)-Math.max(pairStart,start))/60000;overtimeMinutes+=Math.max(0,pairEnd-Math.max(pairStart,end))/60000;row.last_out=p.occurred_at;open=null}}else broken=true}
  if(open||broken||!row.first_in||!row.last_out){row.status='incomplete';issues.push({code:'MISSING_OR_CONFLICTING_PUNCH',shift_id:sh.id,message:'بصمة ناقصة أو تسلسل دخول وخروج متعارض؛ يلزم المراجعة'});return row}
  row.worked_minutes=Math.round(row.worked_minutes);row.late_minutes=Math.max(0,Math.floor((new Date(row.first_in).getTime()-start)/60000)-Number(policy.grace_minutes));row.early_minutes=Math.max(0,Math.floor((end-new Date(row.last_out).getTime())/60000));row.overtime_minutes=Math.floor(overtimeMinutes);const spanMinutes=Math.max(0,Math.min(new Date(row.last_out).getTime(),end)-Math.max(new Date(row.first_in).getTime(),start))/60000;row.unpaid_break_minutes=Math.max(0,Math.floor(spanMinutes-insideMinutes)-Number(policy.paid_break_minutes||0));row.late_deduction=roundMoney((row.late_minutes+row.early_minutes+row.unpaid_break_minutes)/60*hourRate*Number(policy.late_multiplier));row.overtime_pay=roundMoney(row.overtime_minutes/60*overtimeHourRate);return row;
 });
 const absence_deduction=roundMoney(days.reduce((n,d)=>n+d.absence_deduction,0)),late_deduction=roundMoney(days.reduce((n,d)=>n+d.late_deduction,0)),overtime_pay=roundMoney(days.reduce((n,d)=>n+d.overtime_pay,0)),base_salary=Number(employee.monthly_salary||0),fixed_allowance=Number(employee.fixed_allowance||0),transport_allowance=Number(employee.transport_allowance||0),meal_allowance=Number(employee.meal_allowance||0),fixed_incentive=Number(employee.fixed_incentive||0),fixed_deduction=Number(employee.fixed_deduction||0),night_shifts=days.filter(d=>d.status==='present'&&d.night_shift).length,night_shift_pay=roundMoney(night_shifts*Number(employee.night_shift_rate||0));
 const additionTypes=new Set(['allowance','incentive','bonus','night_shift','other_addition']),monthly_additions=roundMoney(adjustments.filter(x=>additionTypes.has(x.type)).reduce((s,x)=>s+Number(x.amount),0)),monthly_deductions=roundMoney(adjustments.filter(x=>!additionTypes.has(x.type)).reduce((s,x)=>s+Number(x.amount),0)),fixed_additions=roundMoney(fixed_allowance+transport_allowance+meal_allowance+fixed_incentive),net_salary=roundMoney(Math.max(0,base_salary+fixed_additions+night_shift_pay+overtime_pay+monthly_additions-absence_deduction-late_deduction-fixed_deduction-monthly_deductions));
 return {employee_id:employee.id,employee_no:employee.employee_no,name:employee.name,job_type:employee.job_type,department:employee.department,whatsapp_phone:employee.whatsapp_phone||employee.phone,salary_transfer_method:employee.salary_transfer_method,salary_transfer_number:employee.salary_transfer_number,daily_work_hours:workingHours,work_days_per_month:workingDays,absence_day_rate:roundMoney(absenceDayRate),overtime_hour_rate:roundMoney(overtimeHourRate),base_salary,fixed_allowance,transport_allowance,meal_allowance,fixed_incentive,fixed_additions,fixed_deduction,night_shifts,night_shift_rate:Number(employee.night_shift_rate||0),night_shift_pay,monthly_additions,monthly_deductions,adjustments,scheduled_shifts:shifts.length,present_shifts:days.filter(d=>d.status==='present').length,absent_shifts:days.filter(d=>d.status==='absent').length,absence_deduction,late_deduction,overtime_pay,net_salary,days,issues};
}
export async function calculatePayroll(db:Database,month:string){validateMonth(month);const policy=(await one(db,"SELECT * FROM attendance_policy WHERE id='default'")).data;const employees=await all(db,'SELECT * FROM hr_employees WHERE active=true ORDER BY name');const shifts=await all(db,"SELECT * FROM attendance_shifts WHERE to_char(shift_date,'YYYY-MM')=$1 ORDER BY starts_at",[month]);const punches=await all(db,"SELECT * FROM attendance_punches WHERE voided=false AND occurred_at>=($1||'-01')::date::timestamp AT TIME ZONE 'Africa/Cairo' - interval '4 hours' AND occurred_at<(($1||'-01')::date+interval '1 month 1 day')::timestamp AT TIME ZONE 'Africa/Cairo' ORDER BY occurred_at",[month]),adjustments=await all(db,'SELECT * FROM payroll_adjustments WHERE month=$1 AND voided=false ORDER BY created_at',[month]);const rows=employees.map(e=>calculateEmployee(e,shifts.filter(s=>s.employee_id===e.id),punches.filter(p=>p.employee_id===e.id),policy,adjustments.filter(x=>x.employee_id===e.id)));const issues=rows.flatMap(e=>e.issues.map((i:any)=>({...i,employee_id:e.employee_id,name:e.name})));if(!employees.length)issues.push({code:'NO_EMPLOYEES',message:'لا يوجد موظفون نشطون',employee_id:'',name:''});const periodFinish=new Date(month+'-01T00:00:00Z');periodFinish.setUTCMonth(periodFinish.getUTCMonth()+1);if(periodFinish.getTime()>Date.now())issues.push({code:'PERIOD_NOT_FINISHED',message:'الشهر لم ينتهِ بعد؛ الكشف مبدئي ولا يعتمد',employee_id:'',name:''});const unmapped=punches.filter(p=>!p.employee_id);if(unmapped.length)issues.push({code:'UNMAPPED_PUNCHES',message:`توجد ${unmapped.length} بصمة غير مربوطة بموظف`,employee_id:'',name:''});return {month,policy,employees:rows,issues,totals:{base_salary:roundMoney(rows.reduce((n,e)=>n+e.base_salary,0)),fixed_additions:roundMoney(rows.reduce((n,e)=>n+e.fixed_additions,0)),night_shift_pay:roundMoney(rows.reduce((n,e)=>n+e.night_shift_pay,0)),monthly_additions:roundMoney(rows.reduce((n,e)=>n+e.monthly_additions,0)),absence_deduction:roundMoney(rows.reduce((n,e)=>n+e.absence_deduction,0)),late_deduction:roundMoney(rows.reduce((n,e)=>n+e.late_deduction,0)),fixed_deduction:roundMoney(rows.reduce((n,e)=>n+e.fixed_deduction,0)),monthly_deductions:roundMoney(rows.reduce((n,e)=>n+e.monthly_deductions,0)),overtime_pay:roundMoney(rows.reduce((n,e)=>n+e.overtime_pay,0)),net_salary:roundMoney(rows.reduce((n,e)=>n+e.net_salary,0))},calculated_at:new Date().toISOString(),basis:'الراتب مربوط بالحضور والانصراف والنوبات المجدولة. يضاف الأساسي والبدلات والحوافز والسهر والإضافي والتسويات الشهرية، وتخصم أيام الغياب والتأخير والخروج المبكر والسلف والخصومات الثابتة والشهرية. كل موظف له قواعد ورقم تحويل مستقلان، والصرف المالي يتم بعد اعتماد الكشف.'}}

