#!/usr/bin/env node
/*
 * Generates every launcher icon and splash asset of the app from the vector
 * brand mark in `mark.cjs` (no flutter_launcher_icons needed).
 *
 *   node tool/brand/generate.cjs            # from mobile/
 *
 * Rasterising uses `sharp` (SVG → PNG). It is not a dependency of the app:
 * the script looks for it in ../backend/node_modules or a global install, or
 * takes SHARP_PATH=/path/to/node_modules/sharp.
 *
 * Output (overwritten):
 *   Android  res/mipmap-*dpi/ic_launcher.png, ic_launcher_round.png (legacy)
 *            res/mipmap-anydpi-v26/ic_launcher(.xml|_round.xml) (adaptive)
 *            res/drawable/ic_launcher_{background,foreground,monochrome}.xml (vectors)
 *            res/drawable*-*dpi/splash_logo.png, launch_background.xml (+ night)
 *            res/values-v31, values-night-v31 styles (Android 12+ splash API)
 *   iOS      AppIcon.appiconset/*.png (opaque), LaunchImage.imageset/*.png
 *   Web      favicon.png, icons/Icon-{192,512}.png, Icon-maskable-{192,512}.png
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { PATH, BLUE, DEEP_CYAN, CYAN, iconSvg } = require('./mark.cjs');

function loadSharp() {
  const candidates = [
    process.env.SHARP_PATH,
    path.resolve(__dirname, '../../../backend/node_modules/sharp'),
    'sharp',
  ].filter(Boolean);
  for (const c of candidates) {
    try {
      return require(c);
    } catch {
      /* next */
    }
  }
  throw new Error('sharp not found: run `npm ci` in backend/ or set SHARP_PATH');
}
const sharp = loadSharp();

const ROOT = path.resolve(__dirname, '../..');
const RES = path.join(ROOT, 'android/app/src/main/res');
const IOS = path.join(ROOT, 'ios/Runner/Assets.xcassets');
const WEB = path.join(ROOT, 'web');

const LIGHT_BG = '#F4F7FC';
const DARK_BG = '#0A1020';

/** Mark scale inside the 108dp adaptive canvas: fits the 66dp safe zone. */
const ADAPTIVE_SCALE = 0.62;

const write = (file, data) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, data);
  console.log('wrote', path.relative(ROOT, file));
};

async function png(svg, size, file, { flatten } = {}) {
  let img = sharp(Buffer.from(svg), { density: 72 * Math.max(1, size / 1024) * 4 }).resize(size, size);
  if (flatten) img = img.flatten({ background: flatten });
  write(file, await img.png({ compressionLevel: 9 }).toBuffer());
}

/** Round (circle-clipped) legacy icon. */
function roundSvg() {
  return iconSvg({ scale: 0.72 }).replace(
    '<svg ',
    '<svg ',
  ).replace(/<rect width="1024" height="1024" fill="url\(#bg\)"\/>/, '<circle cx="512" cy="512" r="512" fill="url(#bg)"/>')
    .replace(/<rect width="1024" height="1024" fill="url\(#glow\)"\/>/, '<circle cx="512" cy="512" r="512" fill="url(#glow)"/>');
}

// ---------------------------------------------------------------- Android --
const DENSITIES = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };

function vectorGroup(fill) {
  const s = ADAPTIVE_SCALE;
  return `    <group
        android:pivotX="512"
        android:pivotY="512"
        android:scaleX="${s}"
        android:scaleY="${s}">
        <path
            android:fillColor="${fill}"
            android:fillType="evenOdd"
            android:pathData="${PATH}" />
    </group>`;
}

const header = (what) =>
  `<?xml version="1.0" encoding="utf-8"?>\n<!-- ${what} Generated by tool/brand/generate.cjs from tool/brand/mark.cjs — do not edit by hand. -->\n`;

async function android() {
  for (const [d, k] of Object.entries(DENSITIES)) {
    await png(iconSvg({ rounded: 180, scale: 0.72 }), Math.round(48 * k), path.join(RES, `mipmap-${d}/ic_launcher.png`));
    await png(roundSvg(), Math.round(48 * k), path.join(RES, `mipmap-${d}/ic_launcher_round.png`));
    // Splash logo: brand tile, 128dp.
    await png(iconSvg({ rounded: 240, scale: 0.72 }), Math.round(128 * k), path.join(RES, `drawable-${d}/splash_logo.png`));
  }

  const adaptive = `${header('Adaptive launcher icon (Android 8+); monochrome = themed icon (Android 13+).')}<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
`;
  write(path.join(RES, 'mipmap-anydpi-v26/ic_launcher.xml'), adaptive);
  write(path.join(RES, 'mipmap-anydpi-v26/ic_launcher_round.xml'), adaptive);

  write(
    path.join(RES, 'drawable/ic_launcher_background.xml'),
    `${header('Adaptive icon background: electric blue → deep cyan with a cyan glow.')}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="1024"
    android:viewportHeight="1024">
    <path android:pathData="M0,0h1024v1024h-1024z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="0"
                android:startY="0"
                android:endX="1024"
                android:endY="1024"
                android:startColor="${BLUE}"
                android:endColor="${DEEP_CYAN}" />
        </aapt:attr>
    </path>
    <path android:pathData="M0,0h1024v1024h-1024z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="radial"
                android:centerX="512"
                android:centerY="800"
                android:gradientRadius="614"
                android:startColor="#99${CYAN.slice(1)}"
                android:endColor="#00${CYAN.slice(1)}" />
        </aapt:attr>
    </path>
</vector>
`,
  );
  const fg = (what, fill) => `${header(what)}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="1024"
    android:viewportHeight="1024">
${vectorGroup(fill)}
</vector>
`;
  write(path.join(RES, 'drawable/ic_launcher_foreground.xml'), fg('Adaptive icon foreground: plug + road mark (safe zone).', '#FFFFFFFF'));
  write(path.join(RES, 'drawable/ic_launcher_monochrome.xml'), fg('Themed (monochrome) icon: the system tints it.', '#FFFFFFFF'));

  const launch = (bg, what) => `${header(what)}<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <color android:color="${bg}" />
    </item>
    <item>
        <bitmap
            android:gravity="center"
            android:src="@drawable/splash_logo" />
    </item>
</layer-list>
`;
  for (const dir of ['drawable', 'drawable-v21']) {
    write(path.join(RES, `${dir}/launch_background.xml`), launch(LIGHT_BG, 'Splash (before Android 12), light.'));
  }
  for (const dir of ['drawable-night', 'drawable-night-v21']) {
    write(path.join(RES, `${dir}/launch_background.xml`), launch(DARK_BG, 'Splash (before Android 12), dark.'));
  }

  const v31 = (bg, parent, what) => `${header(what)}<resources>
    <style name="LaunchTheme" parent="${parent}">
        <item name="android:windowSplashScreenBackground">${bg}</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/ic_launcher_foreground</item>
        <item name="android:windowSplashScreenIconBackgroundColor">${BLUE}</item>
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <style name="NormalTheme" parent="${parent}">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
`;
  write(path.join(RES, 'values-v31/styles.xml'), v31(LIGHT_BG, '@android:style/Theme.Light.NoTitleBar', 'Android 12+ splash screen, light.'));
  write(path.join(RES, 'values-night-v31/styles.xml'), v31(DARK_BG, '@android:style/Theme.Black.NoTitleBar', 'Android 12+ splash screen, dark.'));
}

// -------------------------------------------------------------------- iOS --
async function ios() {
  const set = path.join(IOS, 'AppIcon.appiconset');
  const contents = JSON.parse(fs.readFileSync(path.join(set, 'Contents.json'), 'utf8'));
  const done = new Set();
  for (const img of contents.images) {
    if (!img.filename || done.has(img.filename)) continue;
    done.add(img.filename);
    const pt = parseFloat(img.size);
    const px = Math.round(pt * parseInt(img.scale, 10));
    // iOS masks the corners itself and rejects alpha: square, opaque.
    await png(iconSvg({ scale: 0.72 }), px, path.join(set, img.filename), { flatten: BLUE });
  }
  const launch = path.join(IOS, 'LaunchImage.imageset');
  for (const [name, k] of [['LaunchImage.png', 1], ['LaunchImage@2x.png', 2], ['LaunchImage@3x.png', 3]]) {
    await png(iconSvg({ rounded: 240, scale: 0.72 }), 120 * k, path.join(launch, name));
  }
}

// -------------------------------------------------------------------- Web --
async function web() {
  await png(iconSvg({ rounded: 224, scale: 0.72 }), 32, path.join(WEB, 'favicon.png'));
  await png(iconSvg({ rounded: 224, scale: 0.72 }), 192, path.join(WEB, 'icons/Icon-192.png'));
  await png(iconSvg({ rounded: 224, scale: 0.72 }), 512, path.join(WEB, 'icons/Icon-512.png'));
  await png(iconSvg({ scale: ADAPTIVE_SCALE }), 192, path.join(WEB, 'icons/Icon-maskable-192.png'));
  await png(iconSvg({ scale: ADAPTIVE_SCALE }), 512, path.join(WEB, 'icons/Icon-maskable-512.png'));
}

(async () => {
  await android();
  await ios();
  await web();
  // Store-listing master (Play: 512 px, 32-bit PNG).
  await png(iconSvg({ scale: 0.72 }), 512, path.join(ROOT, 'tool/brand/out/play-store-icon-512.png'));
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
