import { chromium, expect, type Page } from '@playwright/test';
import { createServer } from 'vite';
import { mkdirSync, writeFileSync } from 'node:fs';
import { initDb } from '../server/db.js';
import { seedDatabase } from '../server/seed.js';
import { createApp } from '../server/app.js';

delete process.env.DATABASE_URL;
const db=await initDb(':memory:');await seedDatabase(db);
const app=await createApp(db);
const vite=await createServer({server:{middlewareMode:true,hmr:false},appType:'spa'});app.use(vite.middlewares);
const server=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));
const address=server.address();const base=`http://127.0.0.1:${typeof address==='object'&&address?address.port:0}`;
const browser=await chromium.launch({channel:'chrome',headless:true});
const errors:string[]=[],checks:string[]=[];mkdirSync('docs/screenshots',{recursive:true});
async function login(role:string){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ar-EG',timezoneId:'Africa/Cairo'});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(base);await page.locator('[name=username]').fill(role);await page.locator('[name=password]').fill('Training@2026');await page.getByRole('button',{name:'تسجيل الدخول',exact:true}).click();await page.locator('.sidebar').getByRole('button',{name:'الحضور والرواتب',exact:true}).click();await expect(page.locator('.attendance-module')).toBeVisible();return {context,page}}
async function save(page:Page){const dialog=page.getByRole('dialog');await dialog.locator('button[type=submit]').click();await expect(dialog).toBeHidden()}
async function overflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true)}
const result:any={url:base,database:'isolated in-memory PGlite',checks};
let screenshotPage:Page|undefined;
try{
 const {page}=await login('manager');screenshotPage=page;const module=page.locator('.attendance-module');
 await expect(page.locator('vite-error-overlay')).toHaveCount(0);checks.push('Isolated development page loads without blank page or Vite overlay');
 await module.getByRole('button',{name:'الموظفون',exact:true}).click();await module.getByRole('button',{name:'إضافة موظف',exact:true}).click();const dialog=page.getByRole('dialog');
 await dialog.locator('[name=name]').fill('موظف اختبار واجهة الحضور');await dialog.locator('[name=employee_no]').fill('UI100');await dialog.locator('[name=device_pin]').fill('100');await dialog.locator('[name=user_id]').selectOption('nurse');await dialog.locator('[name=monthly_salary]').fill('3000');await save(page);await expect(module.getByText('UI100',{exact:true})).toBeVisible();
 checks.push('Employee creation stores device PIN, account mapping and salary through UI');
 await module.getByRole('button',{name:'جدول النوبات',exact:true}).click();await module.getByRole('button',{name:'جدولة نوبة',exact:true}).click();await dialog.locator('[name=employee_id]').selectOption({label:'موظف اختبار واجهة الحضور · UI100'});await dialog.locator('[name=shift_date]').fill('2026-08-31');await dialog.locator('[name=start_time]').fill('20:00');await dialog.locator('[name=end_time]').fill('08:00');await save(page);await expect(module.getByText('2026-08-31',{exact:true})).toBeVisible();
 await module.getByRole('button',{name:'سجل البصمات',exact:true}).click();await module.getByRole('button',{name:'استيراد CSV',exact:true}).click();await dialog.locator('[name=csv]').fill('device_pin,occurred_at,event\n100,2026-09-01T08:30:00+03:00,out\n100,2026-08-31T20:20:00+03:00,in');await save(page);await expect(module.locator('tbody tr')).toHaveCount(2);checks.push('Overnight shift and out-of-order CSV punches save and display together');
 await module.getByRole('button',{name:'أجهزة ZK',exact:true}).click();await module.getByRole('button',{name:'إضافة جهاز',exact:true}).click();await dialog.locator('[name=name]').fill('ZK UI device');await dialog.locator('[name=serial]').fill('ZK-UI-100');await save(page);const original=await module.getByLabel('مفتاح الجهاز',{exact:true}).inputValue();expect(original.length).toBeGreaterThan(30);
 await module.getByRole('button',{name:'تجديد المفتاح',exact:true}).click();await save(page);const rotated=await module.getByLabel('مفتاح الجهاز',{exact:true}).inputValue();expect(rotated).not.toBe(original);
 const oldResponse=await fetch(base+'/iclock/cdata?SN=ZK-UI-100',{headers:{'X-Device-Secret':original}}),newResponse=await fetch(base+'/iclock/cdata?SN=ZK-UI-100',{headers:{'X-Device-Secret':rotated}});expect(oldResponse.status).toBe(401);expect(newResponse.status).toBe(200);checks.push('Device secret rotation UI returns a valid new secret and invalidates the previous one');
 await module.getByRole('button',{name:'الرواتب',exact:true}).click();await expect(module.getByLabel('مفتاح الجهاز',{exact:true})).toHaveCount(0);await module.getByLabel('شهر الرواتب').fill('2026-08');await module.getByRole('button',{name:'حساب وعرض الكشف',exact:true}).click();await expect(module.getByRole('heading',{name:'تفاصيل كشف 2026-08',exact:true})).toBeVisible();await expect(module.getByRole('button',{name:'اعتماد وقفل',exact:true})).toBeEnabled();
 await module.getByRole('button',{name:'الموظفون',exact:true}).click();await module.getByRole('button',{name:'تعديل',exact:true}).click();await dialog.locator('[name=monthly_salary]').fill('3200');await save(page);await module.getByRole('button',{name:'الرواتب',exact:true}).click();await expect(module.getByText('تغيرت بيانات المصدر؛ أعد الحساب قبل الاعتماد.',{exact:true})).toBeVisible();await module.getByRole('button',{name:'إعادة الحساب',exact:true}).click();await expect(module.getByText('تغيرت بيانات المصدر؛ أعد الحساب قبل الاعتماد.',{exact:true})).toHaveCount(0);await expect(module.getByRole('button',{name:'اعتماد وقفل',exact:true})).toBeEnabled();checks.push('Payroll preview and recalculation use refreshed optimistic versions after source edits');
 await page.getByRole('button',{name:'EN',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('dir','ltr');await expect(module.getByRole('heading',{name:'Monthly payroll',exact:true})).toBeVisible();if(await page.locator('.toast button').count())await page.locator('.toast button').click();await page.screenshot({path:'docs/screenshots/attendance-payroll-en.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.locator('.sidebar').evaluate(el=>{const box=el.getBoundingClientRect();return box.right<=0||box.left>=window.innerWidth})).toBe(true);await overflow(page);await page.screenshot({path:'docs/screenshots/attendance-mobile-en.png',fullPage:true});await module.getByRole('button',{name:'ZK devices',exact:true}).click();await overflow(page);await expect(module.getByRole('button',{name:'Rotate secret',exact:true})).toBeVisible();await page.getByRole('button',{name:'العربية',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');await overflow(page);await page.screenshot({path:'docs/screenshots/attendance-devices-mobile-ar.png',fullPage:true});checks.push('English/Arabic attendance labels and 390px mobile payroll/devices render without page overflow');
 for(const role of ['nurse','head_nurse']){const own=await login(role);const section=own.page.locator('.attendance-module');await section.getByRole('button',{name:'الموظفون',exact:true}).click();await expect(section.getByText('الأساسي الشهري',{exact:true})).toHaveCount(0);await expect(section.getByRole('button',{name:'الرواتب',exact:true})).toHaveCount(0);const response=await own.page.evaluate(async()=>await(await fetch('/api/attendance')).json());expect(response.employees.every((e:any)=>!Object.hasOwn(e,'monthly_salary'))).toBe(true);if(role==='head_nurse'){await section.getByRole('button',{name:'تعديل',exact:true}).click();await expect(own.page.getByRole('dialog').locator('[name=monthly_salary]')).toHaveCount(0)}await own.context.close()}
 checks.push('Nurse and head nurse UI and API hide salary values and payroll controls');
 const accountant=await login('accountant');const aModule=accountant.page.locator('.attendance-module');await aModule.getByRole('button',{name:'الموظفون',exact:true}).click();await aModule.getByRole('button',{name:'تعديل',exact:true}).click();const aDialog=accountant.page.getByRole('dialog');await expect(aDialog.locator('[name=name]')).toHaveCount(0);await aDialog.locator('[name=monthly_salary]').fill('3300');await save(accountant.page);const actual=await accountant.page.evaluate(async()=>await(await fetch('/api/attendance')).json());expect(Number(actual.employees[0].monthly_salary)).toBe(3300);await accountant.context.close();checks.push('Accountant can edit salary without inadvertently submitting forbidden personnel fields');
 expect(errors).toEqual([]);result.status='PASS';result.javascript_errors=errors;
}catch(error){result.status='FAIL';result.error=String(error);if(screenshotPage)await screenshotPage.screenshot({path:'docs/screenshots/attendance-browser-failure.png',fullPage:true});throw error}finally{writeFileSync('docs/attendance-browser-results.json',JSON.stringify(result,null,2));await browser.close();await vite.close();await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));await db.close()}
console.log(JSON.stringify(result,null,2));
