import {chromium,expect,type Page} from '@playwright/test';
import {createServer} from 'vite';
import {mkdirSync,writeFileSync} from 'node:fs';
import {initDb,one} from '../server/db.js';
import {seedDatabase} from '../server/seed.js';
import {createApp} from '../server/app.js';

delete process.env.DATABASE_URL;const db=await initDb(':memory:');await seedDatabase(db);
const app=await createApp(db);const vite=await createServer({server:{middlewareMode:true,hmr:false},appType:'spa'});app.use(vite.middlewares);
const server=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));const address=server.address() as any;const base=`http://127.0.0.1:${address.port}`;
const browser=await chromium.launch({channel:'chrome',headless:true});const errors:string[]=[],checks:string[]=[];const result:any={database:'isolated in-memory PGlite',url:base,checks};let latest:Page|undefined;mkdirSync('docs/screenshots',{recursive:true});
async function login(role:string){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ar-EG',timezoneId:'Africa/Cairo'});const page=await context.newPage();latest=page;page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('[name=username]').fill(role);await page.locator('[name=password]').fill('Training@2026');await page.getByRole('button',{name:'تسجيل الدخول',exact:true}).click();await page.locator('.sidebar').getByRole('button',{name:'مستهلكات الأطفال',exact:true}).click();await expect(page.locator('.consumables-module')).toBeVisible();return {context,page}}
async function save(page:Page){const dialog=page.getByRole('dialog');await dialog.locator('button[type=submit]').click();await expect(dialog).toBeHidden()}
try{
 const admin=await login('admin');let page=admin.page;let module=page.locator('.consumables-module');await expect(module.getByRole('button',{name:'صرف للطفل',exact:true})).toHaveCount(0);await module.getByRole('button',{name:'إضافة مستهلك',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.locator('[name=sku]').fill('UI-CONS');await dialog.locator('[name=name]').fill('مستهلك تحقق الشاشة');await dialog.locator('[name=unit]').fill('قطعة');await dialog.locator('[name=price]').fill('12.75');await save(page);await expect(module.getByText('مستهلك تحقق الشاشة',{exact:true})).toBeVisible();let row=module.locator('tbody tr').filter({hasText:'UI-CONS'});await row.getByRole('button',{name:'السعر',exact:true}).click();await dialog.locator('[name=price]').fill('13.25');await save(page);checks.push('Admin creates and reprices catalog without bedside issue permission');
 const stock=await login('stock');page=stock.page;module=page.locator('.consumables-module');row=module.locator('tbody tr').filter({hasText:'UI-CONS'});await row.getByRole('button',{name:'استلام',exact:true}).click();dialog=page.getByRole('dialog');await dialog.locator('[name=batch]').fill('UI-BATCH');await dialog.locator('[name=quantity]').fill('10');await dialog.locator('[name=cost]').fill('4.5');await dialog.locator('[name=expires_at]').fill('2029-12-31');await dialog.locator('[name=location]').fill('UI warehouse');await save(page);checks.push('Stock receives batch with optional reorder threshold left blank');
 const nurse=await login('nurse');page=nurse.page;module=page.locator('.consumables-module');await expect(module.getByRole('button',{name:'السعر',exact:true})).toHaveCount(0);await expect(module.getByRole('button',{name:'استلام',exact:true})).toHaveCount(0);row=module.locator('tbody tr').filter({hasText:'UI-CONS'});await row.getByRole('button',{name:'صرف للطفل',exact:true}).click();dialog=page.getByRole('dialog');await dialog.locator('[name=admission_id]').selectOption('admission-1');const mrn=(await one(db,"SELECT mrn FROM patients WHERE id='patient-1'"))!.mrn;await dialog.locator('[name=patient_mrn]').fill(mrn);await dialog.locator('[name=quantity]').fill('2');await save(page);await expect(module.locator('tbody tr').filter({hasText:'UI-CONS'})).toHaveCount(1);await expect(module.locator('tbody tr').filter({hasText:'مستهلك تحقق الشاشة'})).toHaveCount(2);const record=await one(db,"SELECT c.amount,c.quantity,i.quantity AS remaining FROM consumptions c JOIN consumable_catalog cat ON cat.id=c.consumable_id JOIN inventory i ON i.consumable_id=cat.id WHERE cat.sku='UI-CONS'");expect(Number(record!.amount)).toBe(26.5);expect(Number(record!.remaining)).toBe(8);checks.push('Nurse selects infant and issues two units: one 26.50 EGP charge and stock reduced to eight');
 await page.getByRole('button',{name:'EN',exact:true}).click();await expect(module.getByRole('heading',{name:'Medical consumables',exact:true})).toBeVisible();await expect(module.getByRole('heading',{name:'Consumable issue history',exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);await page.screenshot({path:'docs/screenshots/consumables-mobile-en.png',fullPage:true});await page.getByRole('button',{name:'العربية',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);await page.screenshot({path:'docs/screenshots/consumables-mobile-ar.png',fullPage:true});checks.push('Arabic and English controls and 390px mobile view render without page overflow');
 expect(errors).toEqual([]);result.status='PASS';result.javascript_errors=errors;
}catch(e){result.status='FAIL';result.error=String(e);if(latest)await latest.screenshot({path:'docs/screenshots/consumables-browser-failure.png',fullPage:true});throw e}finally{writeFileSync('docs/consumables-browser-results.json',JSON.stringify(result,null,2));await browser.close();await vite.close();await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));await db.close()}
console.log(JSON.stringify(result,null,2));
