import express from 'express';
import {resolve} from 'node:path';
import {mkdirSync,writeFileSync} from 'node:fs';
import {chromium,expect} from '@playwright/test';
import {initDb,one} from '../server/db.js';
import {seedDatabase} from '../server/seed.js';
import {createApp} from '../server/app.js';

delete process.env.DATABASE_URL;
const db=await initDb(':memory:');await seedDatabase(db);const app=await createApp(db);app.use(express.static(resolve('dist')));app.use((_r,s)=>s.sendFile(resolve('dist/index.html')));
const server=app.listen(0,'127.0.0.1');await new Promise<void>(done=>server.once('listening',done));const origin=`http://127.0.0.1:${(server.address() as any).port}`;
const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ar-EG',timezoneId:'Africa/Cairo',serviceWorkers:'block'});const page=await context.newPage();const errors:string[]=[],checks:string[]=[];const result:any={database:'isolated in-memory PGlite',frontend:'existing dist production build',origin,checks};page.on('pageerror',e=>errors.push(e.message));mkdirSync('docs/screenshots',{recursive:true});
try{
 const login=await fetch(origin+'/api/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({username:'admin',password:'Training@2026'})});expect(login.status).toBe(200);const cookie=login.headers.get('set-cookie')!.split(';')[0];
 const child=await one(db,"SELECT p.name,p.mrn,u.name AS nurse_name FROM patients p JOIN users u ON u.id='nurse' WHERE p.id='patient-1'");const beforeCharges=Number((await one(db,'SELECT count(*) AS n FROM charges'))!.n);
 await page.goto(origin);await page.locator('[name=username]').fill('nurse');await page.locator('[name=password]').fill('Training@2026');await page.getByRole('button',{name:'تسجيل الدخول',exact:true}).click();await page.getByRole('button',{name:'EN',exact:true}).click();await page.locator('.sidebar').getByRole('button',{name:'Monitors & nursing readings',exact:true}).click();
 const module=page.locator('.monitoring-module');await expect(module.getByText('Devices are not network-connected — manual entry',{exact:true})).toBeVisible();await expect(module).toContainText('not a live device feed');await expect(module).toContainText('does not replace the device display or its alarms');checks.push('Production UI explicitly identifies manual records and does not claim a live device feed');
 await module.getByRole('searchbox').fill(child!.mrn);let card=page.locator('.monitoring-grid .panel').filter({hasText:child!.mrn});await expect(card).toHaveCount(1);checks.push('Nurse can find the admitted infant without linking a network device');
 await card.getByRole('button',{name:'Add manual reading',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.locator('[name=confirm_mrn]').fill(child!.mrn);const currentMinute=await page.evaluate(()=>{const now=new Date(Date.now()-60000);return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16)});await dialog.locator('[name=measured_at]').fill(currentMinute);await dialog.locator('[name=heart_rate]').fill('149');await dialog.locator('[name=respiratory_rate]').fill('47');await dialog.locator('[name=spo2]').fill('98');await dialog.locator('[name=temperature]').fill('36.8');await dialog.locator('[name=bilirubin_total]').fill('12.4');await dialog.locator('[name=bilirubin_direct]').fill('0.8');await dialog.locator('[name=bilirubin_method]').selectOption('transcutaneous');await dialog.locator('[name=notes]').fill('Isolated browser proof — manual observation');await dialog.locator('button[type=submit]').click();await expect(dialog).toBeHidden();await expect(card.locator('.monitor-values')).toContainText('149');await expect(card.locator('.monitor-values')).toContainText('36.8');await expect(card.locator('.monitor-values')).toContainText('12.4');await expect(card).toContainText(child!.nurse_name);await expect(card).toContainText('Saved manual reading');
 const stored=await one(db,"SELECT * FROM vitals WHERE admission_id='admission-1' ORDER BY created_at DESC LIMIT 1");expect(stored!.actor_id).toBe('nurse');expect(stored!.source).toBe('manual');expect(stored!.monitor_binding_id).toBeNull();expect(Number(stored!.heart_rate)).toBe(149);expect(Number(stored!.bilirubin_total)).toBe(12.4);expect(Number(stored!.bilirubin_direct)).toBe(0.8);expect(Number((await one(db,'SELECT count(*) AS n FROM charges'))!.n)).toBe(beforeCharges);checks.push('Manual monitor and bilirubin readings persist without a device link and without a billing side effect');
 await page.screenshot({path:'docs/screenshots/monitoring-manual-desktop-en.png',fullPage:true});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);await expect(card.getByRole('button',{name:'Add manual reading',exact:true})).toBeVisible();await page.screenshot({path:'docs/screenshots/monitoring-manual-mobile-en.png',fullPage:true});checks.push('390px monitoring view fits without horizontal page overflow');
 await card.getByRole('button',{name:'Nursing chart',exact:true}).click();await expect(page).toHaveURL(/tab=nursing/);await expect(page.locator('.content').getByRole('cell',{name:'149',exact:true})).toBeVisible();await expect(page.locator('.content').getByRole('cell',{name:'149',exact:true}).locator('..').getByRole('cell',{name:'36.8',exact:true})).toBeVisible();checks.push('Nursing chart navigation displays the same persisted manual reading');
 expect(errors).toEqual([]);result.status='PASS';result.javascript_errors=errors;
}catch(error){result.status='FAIL';result.error=String(error);await page.screenshot({path:'docs/screenshots/monitoring-browser-failure.png',fullPage:true});throw error}finally{writeFileSync('docs/monitoring-browser-results.json',JSON.stringify(result,null,2));await browser.close();await new Promise<void>((done,reject)=>server.close(error=>error?reject(error):done()));await db.close()}
console.log(JSON.stringify(result,null,2));
