import express from 'express';
import {resolve} from 'node:path';
import {chromium,expect} from '@playwright/test';
import {initDb} from '../server/db.js';
import {createApp} from '../server/app.js';

delete process.env.DATABASE_URL;const db=await initDb(':memory:'),app=await createApp(db,{seed:true});app.use(express.static(resolve('dist')));app.use((_r,s)=>s.sendFile(resolve('dist/index.html')));const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const origin=`http://127.0.0.1:${(server.address() as any).port}`,browser=await chromium.launch({channel:'chrome',headless:true}),errors:string[]=[],checks:string[]=[];
async function login(username:string){const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ar-EG',timezoneId:'Africa/Cairo',serviceWorkers:'block'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.locator('[name=username]').fill(username);await page.locator('[name=password]').fill('Training@2026');await page.getByRole('button',{name:'تسجيل الدخول',exact:true}).click();await expect(page.locator('.sidebar nav')).toBeVisible();return{context,page}}
try{
 const admin=await login('admin');await admin.page.locator('[data-page=accounts]').click();await expect(admin.page.locator('.accounting-workspace')).toBeVisible();await expect(admin.page.getByRole('heading',{name:'طلبات الصرف الداخلية',exact:true})).toBeVisible();await expect(admin.page.getByRole('heading',{name:'طلبات وأوامر الشراء',exact:true})).toBeVisible();await expect(admin.page.locator('.sidebar [data-page=purchases]')).toHaveCount(0);checks.push('Accounts includes suppliers, internal requests and purchase orders without duplicate admin sidebar section');
 await admin.page.getByRole('button',{name:'أمر شراء جديد',exact:true}).click();let dialog=admin.page.getByRole('dialog');await expect(dialog.locator('[name=section_0]')).toBeVisible();await expect(dialog.locator('[name=unit_cost_0]')).toHaveCount(0);await dialog.getByRole('button',{name:'إلغاء',exact:true}).click();checks.push('Purchase request chooses stock destination without exposing or requiring prices');
 await admin.page.locator('[data-page=attendance]').click();await admin.page.getByRole('button',{name:'الموظفون',exact:true}).click();await admin.page.getByRole('button',{name:'إضافة موظف',exact:true}).click();dialog=admin.page.getByRole('dialog');for(const name of ['whatsapp_phone','monthly_salary','fixed_allowance','transport_allowance','meal_allowance','fixed_incentive','night_shift_rate','fixed_deduction','salary_transfer_method','salary_transfer_number'])await expect(dialog.locator(`[name=${name}]`)).toBeVisible();await dialog.getByRole('button',{name:'إلغاء',exact:true}).click();checks.push('Employee form includes WhatsApp, individual salary, allowances, incentives, nights, deductions and transfer details');await admin.context.close();
 const reception=await login('reception');await expect(reception.page.locator('.sidebar [data-page=purchases]')).toBeVisible();await reception.page.locator('[data-page=purchases]').click();await expect(reception.page.getByRole('button',{name:'طلب صرف من المخزن',exact:true})).toBeVisible();await expect(reception.page.getByRole('button',{name:'أمر شراء جديد',exact:true})).toHaveCount(0);await reception.page.getByRole('button',{name:'طلب صرف من المخزن',exact:true}).click();dialog=reception.page.getByRole('dialog');await expect(dialog.locator('[name=section_0]')).toBeVisible();await expect(dialog.locator('[name=unit_cost_0]')).toHaveCount(0);checks.push('Reception requests stock without prices while external purchasing remains with Stock, Purchasing or Accounts');await reception.page.setViewportSize({width:390,height:844});await expect.poll(()=>reception.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true);checks.push('Procurement UI fits a 390px mobile viewport');await reception.context.close();expect(errors).toEqual([]);console.log(JSON.stringify({status:'PASS',checks,javascript_errors:errors},null,2));
}finally{await browser.close();await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));await db.close()}
