/**
 * Reference data (NOT sample content): currencies, markets, connector types,
 * default app settings, spec definitions and search aliases.
 * Values here are generic reference facts or product defaults — no news,
 * prices, stations or vehicle data.
 */

export const CURRENCIES = [
  {
    code: 'EGP',
    nameAr: 'جنيه مصري',
    nameEn: 'Egyptian Pound',
    symbolAr: 'ج.م',
    symbolEn: 'E£',
    decimals: 2,
  },
  {
    code: 'SAR',
    nameAr: 'ريال سعودي',
    nameEn: 'Saudi Riyal',
    symbolAr: 'ر.س',
    symbolEn: 'SAR',
    decimals: 2,
  },
  {
    code: 'AED',
    nameAr: 'درهم إماراتي',
    nameEn: 'UAE Dirham',
    symbolAr: 'د.إ',
    symbolEn: 'AED',
    decimals: 2,
  },
  // Source currencies for foreign prices (shown only as labelled conversions).
  {
    code: 'USD',
    nameAr: 'دولار أمريكي',
    nameEn: 'US Dollar',
    symbolAr: '$',
    symbolEn: '$',
    decimals: 2,
  },
  { code: 'EUR', nameAr: 'يورو', nameEn: 'Euro', symbolAr: '€', symbolEn: '€', decimals: 2 },
  {
    code: 'CNY',
    nameAr: 'يوان صيني',
    nameEn: 'Chinese Yuan',
    symbolAr: '¥',
    symbolEn: '¥',
    decimals: 2,
  },
] as const;

/** Launch market EG (default) plus SA and AE. More can be added from admin. */
export const MARKETS = [
  {
    code: 'EG',
    nameAr: 'مصر',
    nameEn: 'Egypt',
    currencyCode: 'EGP',
    timezone: 'Africa/Cairo',
    defaultLanguage: 'ar',
    sortOrder: 1,
  },
  {
    code: 'SA',
    nameAr: 'السعودية',
    nameEn: 'Saudi Arabia',
    currencyCode: 'SAR',
    timezone: 'Asia/Riyadh',
    defaultLanguage: 'ar',
    sortOrder: 2,
  },
  {
    code: 'AE',
    nameAr: 'الإمارات',
    nameEn: 'United Arab Emirates',
    currencyCode: 'AED',
    timezone: 'Asia/Dubai',
    defaultLanguage: 'ar',
    sortOrder: 3,
  },
] as const;

/**
 * Connector standards. `typicalMax*Kw` are informational typical values of
 * the standard (NOT a statement about any station); every connector row
 * stores its own max_power_kw. `aliases` help map provider names (e.g. Open
 * Charge Map connection types) and must be verified by the stations importer.
 */
export const CONNECTOR_TYPES = [
  {
    code: 'type1',
    nameEn: 'Type 1 (J1772)',
    nameAr: 'النوع 1 (J1772)',
    supportsAc: true,
    supportsDc: false,
    typicalMaxAcKw: '7.4',
    typicalMaxDcKw: null,
    standard: 'SAE J1772 / IEC 62196-2 Type 1',
    aliases: ['Type 1 (J1772)', 'J1772', 'SAE J1772'],
    iconKey: 'type1',
    sortOrder: 60,
  },
  {
    code: 'type2',
    nameEn: 'Type 2 (Mennekes)',
    nameAr: 'النوع 2 (منيكس)',
    supportsAc: true,
    supportsDc: false,
    typicalMaxAcKw: '22',
    typicalMaxDcKw: null,
    standard: 'IEC 62196-2 Type 2',
    aliases: [
      'Type 2 (Socket Only)',
      'Type 2 (Tethered Connector)',
      'Mennekes (Type 2)',
      'IEC 62196-2 Type 2',
    ],
    iconKey: 'type2',
    sortOrder: 10,
  },
  {
    code: 'ccs2',
    nameEn: 'CCS2 (Combo 2)',
    nameAr: 'CCS2 (كومبو 2)',
    supportsAc: false,
    supportsDc: true,
    typicalMaxAcKw: null,
    typicalMaxDcKw: '350',
    standard: 'IEC 62196-3 Combo 2',
    aliases: ['CCS (Type 2)', 'Combo 2', 'CCS2'],
    iconKey: 'ccs2',
    sortOrder: 20,
  },
  {
    code: 'ccs1',
    nameEn: 'CCS1 (Combo 1)',
    nameAr: 'CCS1 (كومبو 1)',
    supportsAc: false,
    supportsDc: true,
    typicalMaxAcKw: null,
    typicalMaxDcKw: '350',
    standard: 'SAE J1772 Combo 1',
    aliases: ['CCS (Type 1)', 'Combo 1', 'SAE Combo', 'CCS1'],
    iconKey: 'ccs1',
    sortOrder: 50,
  },
  {
    code: 'chademo',
    nameEn: 'CHAdeMO',
    nameAr: 'تشاديمو (CHAdeMO)',
    supportsAc: false,
    supportsDc: true,
    typicalMaxAcKw: null,
    typicalMaxDcKw: '62.5',
    standard: 'CHAdeMO / IEC 62196-3 AA',
    aliases: ['CHAdeMO'],
    iconKey: 'chademo',
    sortOrder: 40,
  },
  {
    code: 'nacs',
    nameEn: 'NACS (SAE J3400)',
    nameAr: 'NACS (تسلا / SAE J3400)',
    supportsAc: true,
    supportsDc: true,
    typicalMaxAcKw: '11.5',
    typicalMaxDcKw: '250',
    standard: 'SAE J3400',
    aliases: ['NACS / Tesla Supercharger', 'Tesla (Model S/X)', 'NACS', 'SAE J3400'],
    iconKey: 'nacs',
    sortOrder: 70,
  },
  {
    code: 'gbt_ac',
    nameEn: 'GB/T AC',
    nameAr: 'GB/T تيار متردد',
    supportsAc: true,
    supportsDc: false,
    typicalMaxAcKw: '7',
    typicalMaxDcKw: null,
    standard: 'GB/T 20234.2',
    aliases: [
      'GB-T AC - GB/T 20234.2 (Socket)',
      'GB-T AC - GB/T 20234.2 (Tethered Cable)',
      'GB/T AC',
    ],
    iconKey: 'gbt_ac',
    sortOrder: 30,
  },
  {
    code: 'gbt_dc',
    nameEn: 'GB/T DC',
    nameAr: 'GB/T تيار مستمر',
    supportsAc: false,
    supportsDc: true,
    typicalMaxAcKw: null,
    typicalMaxDcKw: '250',
    standard: 'GB/T 20234.3',
    aliases: ['GB-T DC - GB/T 20234.3', 'GB/T DC'],
    iconKey: 'gbt_dc',
    sortOrder: 35,
  },
] as const;

/**
 * Default app settings. Seeded only when the key does not exist yet, so
 * admin edits are never overwritten. `isPublic` keys feed GET /app-config.
 */
export const APP_SETTINGS: {
  key: string;
  isPublic: boolean;
  description: string;
  value: unknown;
}[] = [
  {
    key: 'branding',
    isPublic: true,
    description: 'App name, logo and brand colors (overridable from admin).',
    value: {
      appName: 'EV Car News',
      logoUrl: null,
      primaryColor: '#0A5CFF',
      accentColor: '#00C2E0',
    },
  },
  {
    key: 'defaults',
    isPublic: true,
    description: 'Default language and market; supported languages.',
    value: { defaultLanguage: 'ar', defaultMarket: 'EG', languages: ['ar', 'en'] },
  },
  {
    key: 'home.sections',
    isPublic: true,
    description: 'Home sections order and visibility.',
    value: [
      { key: 'top_story', enabled: true, order: 1 },
      { key: 'latest_news', enabled: true, order: 2 },
      { key: 'interior_tours', enabled: true, order: 3 },
      { key: 'new_cars', enabled: true, order: 4 },
      { key: 'featured_comparisons', enabled: true, order: 5 },
      { key: 'reviews', enabled: true, order: 6 },
      { key: 'nearby_stations', enabled: true, order: 7 },
      { key: 'charging_guides', enabled: true, order: 8 },
    ],
  },
  {
    key: 'features',
    isPublic: true,
    description:
      'Feature flags. A feature is only announced to the apps when its flag is on AND its module is implemented (IMPLEMENTED_FEATURES); features that depend on external services also need them configured. Everything starts off until it ships.',
    value: {
      news: false,
      cars: false,
      comparisons: false,
      interiorTours: false,
      stations: false,
      calculators: false,
      garage: false,
      favorites: false,
      chargingLogs: false,
      reminders: false,
      encyclopedia: false,
      notifications: false,
      community: false,
      tripPlanner: false,
      servicesDirectory: false,
      assistant: false,
      ads: false,
      exteriorSpin: false,
    },
  },
  {
    key: 'share',
    isPublic: true,
    description: 'Share link settings (canonical web base URL and path templates).',
    value: {
      baseUrl: 'https://evcar.news',
      paths: { article: '/n/{slug}', car: '/cars/{slug}', comparison: '/compare/{shareId}' },
      defaultImageUrl: null,
    },
  },
  {
    key: 'legal',
    isPublic: true,
    description: 'Legal page URLs (null until the pages exist).',
    value: { privacyUrl: null, termsUrl: null },
  },
  {
    key: 'map',
    isPublic: true,
    description:
      'Map tiles. The public OSM tile server has a strict usage policy; configure your own tile provider for production.',
    value: {
      tileUrlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
      attribution: '© OpenStreetMap contributors',
      maxZoom: 19,
    },
  },
  {
    key: 'app_links',
    isPublic: false,
    description: 'Android App Links / iOS Universal Links (served by the share module).',
    value: {
      androidPackage: 'news.evcar.app',
      androidSha256CertFingerprints: [],
      iosTeamId: null,
      iosBundleId: 'news.evcar.app',
    },
  },
];

type SpecDef = {
  key: string;
  group: string;
  dataType: 'number' | 'text' | 'boolean';
  unit?: string;
  betterDirection?: 'higher' | 'lower' | 'none';
  labelEn: string;
  labelAr: string;
  isKeySpec?: boolean;
  descriptionEn?: string;
};

/**
 * Spec keys with canonical units and "better" direction for comparisons.
 * NOT specs: range (range_measurements, with cycle), consumption
 * (consumption_measurements, with cycle — never compared across cycles),
 * charging times (charging_time_measurements, with SoC window and charger
 * power) and charging ports (variant_market_inlets, per market, linked to
 * connector_types). Battery capacity is context, not a "bigger wins" metric
 * (betterDirection none, REQUIREMENTS §7).
 */
export const SPEC_DEFINITIONS: SpecDef[] = [
  // battery
  {
    key: 'battery.gross_kwh',
    group: 'battery',
    dataType: 'number',
    unit: 'kWh',
    betterDirection: 'none',
    labelEn: 'Battery capacity (gross)',
    labelAr: 'سعة البطارية الإجمالية',
    isKeySpec: true,
  },
  {
    key: 'battery.usable_kwh',
    group: 'battery',
    dataType: 'number',
    unit: 'kWh',
    betterDirection: 'none',
    labelEn: 'Battery capacity (usable)',
    labelAr: 'سعة البطارية القابلة للاستخدام',
    isKeySpec: true,
  },
  {
    key: 'battery.chemistry',
    group: 'battery',
    dataType: 'text',
    labelEn: 'Battery chemistry',
    labelAr: 'كيمياء البطارية',
  },
  {
    key: 'battery.voltage_v',
    group: 'battery',
    dataType: 'number',
    unit: 'V',
    betterDirection: 'none',
    labelEn: 'System voltage',
    labelAr: 'جهد النظام',
  },
  {
    key: 'battery.warranty_years',
    group: 'battery',
    dataType: 'number',
    unit: 'year',
    betterDirection: 'higher',
    labelEn: 'Battery warranty (years)',
    labelAr: 'ضمان البطارية (سنوات)',
  },
  {
    key: 'battery.warranty_km',
    group: 'battery',
    dataType: 'number',
    unit: 'km',
    betterDirection: 'higher',
    labelEn: 'Battery warranty (distance)',
    labelAr: 'ضمان البطارية (مسافة)',
  },
  // charging (ports: variant_market_inlets; consumption: consumption_measurements)
  {
    key: 'charging.ac_max_kw',
    group: 'charging',
    dataType: 'number',
    unit: 'kW',
    betterDirection: 'higher',
    labelEn: 'Max AC charging power',
    labelAr: 'أقصى قدرة شحن AC',
    isKeySpec: true,
  },
  {
    key: 'charging.dc_peak_kw',
    group: 'charging',
    dataType: 'number',
    unit: 'kW',
    betterDirection: 'higher',
    labelEn: 'Peak DC charging power',
    labelAr: 'أقصى قدرة شحن DC (ذروة)',
    isKeySpec: true,
    descriptionEn: 'Peak, not average power. Use charging curves/times for realistic durations.',
  },
  {
    key: 'charging.ac_phases',
    group: 'charging',
    dataType: 'number',
    betterDirection: 'none',
    labelEn: 'On-board charger phases',
    labelAr: 'أطوار الشاحن المدمج',
  },
  {
    key: 'charging.v2l',
    group: 'charging',
    dataType: 'boolean',
    labelEn: 'Vehicle-to-load (V2L)',
    labelAr: 'تغذية الأجهزة (V2L)',
  },
  {
    key: 'charging.v2l_max_kw',
    group: 'charging',
    dataType: 'number',
    unit: 'kW',
    betterDirection: 'higher',
    labelEn: 'V2L max power',
    labelAr: 'أقصى قدرة V2L',
  },
  {
    key: 'charging.battery_preconditioning',
    group: 'charging',
    dataType: 'boolean',
    labelEn: 'Battery preconditioning',
    labelAr: 'التهيئة الحرارية للبطارية',
  },
  {
    key: 'charging.plug_and_charge',
    group: 'charging',
    dataType: 'boolean',
    labelEn: 'Plug & Charge',
    labelAr: 'الشحن بالتوصيل المباشر (Plug & Charge)',
  },
  // performance
  {
    key: 'performance.power_kw',
    group: 'performance',
    dataType: 'number',
    unit: 'kW',
    betterDirection: 'higher',
    labelEn: 'System power (kW)',
    labelAr: 'القوة (كيلوواط)',
    isKeySpec: true,
  },
  {
    key: 'performance.power_hp',
    group: 'performance',
    dataType: 'number',
    unit: 'hp',
    betterDirection: 'higher',
    labelEn: 'System power (hp)',
    labelAr: 'القوة (حصان)',
  },
  {
    key: 'performance.torque_nm',
    group: 'performance',
    dataType: 'number',
    unit: 'Nm',
    betterDirection: 'higher',
    labelEn: 'Torque',
    labelAr: 'عزم الدوران',
    isKeySpec: true,
  },
  {
    key: 'performance.accel_0_100_s',
    group: 'performance',
    dataType: 'number',
    unit: 's',
    betterDirection: 'lower',
    labelEn: '0–100 km/h',
    labelAr: 'التسارع 0–100 كم/س',
    isKeySpec: true,
  },
  {
    key: 'performance.top_speed_kmh',
    group: 'performance',
    dataType: 'number',
    unit: 'km/h',
    betterDirection: 'higher',
    labelEn: 'Top speed',
    labelAr: 'السرعة القصوى',
  },
  {
    key: 'performance.motors',
    group: 'performance',
    dataType: 'number',
    betterDirection: 'none',
    labelEn: 'Number of electric motors',
    labelAr: 'عدد المحركات الكهربائية',
  },
  {
    key: 'performance.engine_displacement_l',
    group: 'performance',
    dataType: 'number',
    unit: 'l',
    betterDirection: 'none',
    labelEn: 'Engine displacement (hybrids)',
    labelAr: 'سعة المحرك (الهجينة)',
  },
  // dimensions & practicality
  {
    key: 'dimensions.length_mm',
    group: 'dimensions',
    dataType: 'number',
    unit: 'mm',
    betterDirection: 'none',
    labelEn: 'Length',
    labelAr: 'الطول',
  },
  {
    key: 'dimensions.width_mm',
    group: 'dimensions',
    dataType: 'number',
    unit: 'mm',
    betterDirection: 'none',
    labelEn: 'Width',
    labelAr: 'العرض',
  },
  {
    key: 'dimensions.height_mm',
    group: 'dimensions',
    dataType: 'number',
    unit: 'mm',
    betterDirection: 'none',
    labelEn: 'Height',
    labelAr: 'الارتفاع',
  },
  {
    key: 'dimensions.wheelbase_mm',
    group: 'dimensions',
    dataType: 'number',
    unit: 'mm',
    betterDirection: 'higher',
    labelEn: 'Wheelbase',
    labelAr: 'قاعدة العجلات',
  },
  {
    key: 'dimensions.ground_clearance_mm',
    group: 'dimensions',
    dataType: 'number',
    unit: 'mm',
    betterDirection: 'higher',
    labelEn: 'Ground clearance',
    labelAr: 'الخلوص الأرضي',
  },
  {
    key: 'dimensions.curb_weight_kg',
    group: 'dimensions',
    dataType: 'number',
    unit: 'kg',
    betterDirection: 'lower',
    labelEn: 'Curb weight',
    labelAr: 'الوزن فارغة',
  },
  {
    key: 'practicality.trunk_l',
    group: 'practicality',
    dataType: 'number',
    unit: 'l',
    betterDirection: 'higher',
    labelEn: 'Trunk volume',
    labelAr: 'سعة الصندوق',
  },
  {
    key: 'practicality.trunk_max_l',
    group: 'practicality',
    dataType: 'number',
    unit: 'l',
    betterDirection: 'higher',
    labelEn: 'Max cargo volume (seats folded)',
    labelAr: 'أقصى سعة تخزين (المقاعد مطوية)',
  },
  {
    key: 'practicality.frunk_l',
    group: 'practicality',
    dataType: 'number',
    unit: 'l',
    betterDirection: 'higher',
    labelEn: 'Front trunk (frunk)',
    labelAr: 'الصندوق الأمامي',
  },
  {
    key: 'practicality.towing_braked_kg',
    group: 'practicality',
    dataType: 'number',
    unit: 'kg',
    betterDirection: 'higher',
    labelEn: 'Towing capacity (braked)',
    labelAr: 'قدرة القطر (بفرامل)',
  },
  // safety
  {
    key: 'safety.airbags',
    group: 'safety',
    dataType: 'number',
    betterDirection: 'higher',
    labelEn: 'Airbags',
    labelAr: 'الوسائد الهوائية',
  },
  {
    key: 'safety.ncap_rating',
    group: 'safety',
    dataType: 'text',
    labelEn: 'Crash test rating',
    labelAr: 'تقييم اختبار التصادم',
  },
  {
    key: 'safety.aeb',
    group: 'safety',
    dataType: 'boolean',
    labelEn: 'Automatic emergency braking',
    labelAr: 'الكبح التلقائي في حالات الطوارئ',
  },
  {
    key: 'safety.lane_keeping',
    group: 'safety',
    dataType: 'boolean',
    labelEn: 'Lane keeping assist',
    labelAr: 'مساعد البقاء في المسار',
  },
  {
    key: 'safety.blind_spot',
    group: 'safety',
    dataType: 'boolean',
    labelEn: 'Blind-spot monitoring',
    labelAr: 'مراقبة النقطة العمياء',
  },
  {
    key: 'safety.adaptive_cruise',
    group: 'safety',
    dataType: 'boolean',
    labelEn: 'Adaptive cruise control',
    labelAr: 'مثبت السرعة التكيفي',
  },
  {
    key: 'safety.camera_360',
    group: 'safety',
    dataType: 'boolean',
    labelEn: '360° camera',
    labelAr: 'كاميرا 360°',
  },
  // comfort & tech
  {
    key: 'comfort.heat_pump',
    group: 'comfort',
    dataType: 'boolean',
    labelEn: 'Heat pump',
    labelAr: 'مضخة حرارية',
  },
  {
    key: 'comfort.panoramic_roof',
    group: 'comfort',
    dataType: 'boolean',
    labelEn: 'Panoramic roof',
    labelAr: 'سقف بانورامي',
  },
  {
    key: 'comfort.ventilated_seats',
    group: 'comfort',
    dataType: 'boolean',
    labelEn: 'Ventilated front seats',
    labelAr: 'مقاعد أمامية مهواة',
  },
  {
    key: 'comfort.heated_seats',
    group: 'comfort',
    dataType: 'boolean',
    labelEn: 'Heated front seats',
    labelAr: 'مقاعد أمامية مدفأة',
  },
  {
    key: 'tech.screen_in',
    group: 'tech',
    dataType: 'number',
    unit: 'in',
    betterDirection: 'none',
    labelEn: 'Central screen size',
    labelAr: 'حجم الشاشة المركزية',
  },
  {
    key: 'tech.apple_carplay',
    group: 'tech',
    dataType: 'boolean',
    labelEn: 'Apple CarPlay',
    labelAr: 'Apple CarPlay',
  },
  {
    key: 'tech.android_auto',
    group: 'tech',
    dataType: 'boolean',
    labelEn: 'Android Auto',
    labelAr: 'Android Auto',
  },
  {
    key: 'tech.ota_updates',
    group: 'tech',
    dataType: 'boolean',
    labelEn: 'Over-the-air updates',
    labelAr: 'تحديثات البرمجيات عن بُعد',
  },
  // warranty
  {
    key: 'warranty.vehicle_years',
    group: 'warranty',
    dataType: 'number',
    unit: 'year',
    betterDirection: 'higher',
    labelEn: 'Vehicle warranty (years)',
    labelAr: 'ضمان السيارة (سنوات)',
  },
  {
    key: 'warranty.vehicle_km',
    group: 'warranty',
    dataType: 'number',
    unit: 'km',
    betterDirection: 'higher',
    labelEn: 'Vehicle warranty (distance)',
    labelAr: 'ضمان السيارة (مسافة)',
  },
];

/** Alternative spellings / transliterations (contract §4.7). */
export const SEARCH_ALIASES: { term: string; canonical: string }[] = [
  { term: 'بي واي دي', canonical: 'BYD' },
  { term: 'بى واى دى', canonical: 'BYD' },
  { term: 'تسلا', canonical: 'Tesla' },
  { term: 'تيسلا', canonical: 'Tesla' },
  { term: 'زيكر', canonical: 'Zeekr' },
  { term: 'زيكير', canonical: 'Zeekr' },
  { term: 'شاومي', canonical: 'Xiaomi' },
  { term: 'شياومي', canonical: 'Xiaomi' },
  { term: 'بي ام دبليو', canonical: 'BMW' },
  { term: 'بي إم دبليو', canonical: 'BMW' },
  { term: 'فولكس فاجن', canonical: 'Volkswagen' },
  { term: 'فولكسفاجن', canonical: 'Volkswagen' },
  { term: 'فولكس واجن', canonical: 'Volkswagen' },
  { term: 'VW', canonical: 'Volkswagen' },
  { term: 'هيونداي', canonical: 'Hyundai' },
  { term: 'هيونداى', canonical: 'Hyundai' },
  { term: 'كيا', canonical: 'Kia' },
  { term: 'ام جي', canonical: 'MG' },
  { term: 'إم جي', canonical: 'MG' },
  { term: 'نيو', canonical: 'NIO' },
  { term: 'اكسبنج', canonical: 'XPeng' },
  { term: 'إكس بنغ', canonical: 'XPeng' },
  { term: 'مرسيدس', canonical: 'Mercedes-Benz' },
  { term: 'اودي', canonical: 'Audi' },
  { term: 'بورشه', canonical: 'Porsche' },
  { term: 'فولفو', canonical: 'Volvo' },
  { term: 'تويوتا', canonical: 'Toyota' },
  { term: 'نيسان', canonical: 'Nissan' },
  { term: 'شيري', canonical: 'Chery' },
  { term: 'جيلي', canonical: 'Geely' },
  { term: 'هونشي', canonical: 'Hongqi' },
  { term: 'شاحن', canonical: 'charger' },
  { term: 'محطة شحن', canonical: 'charging station' },
  { term: 'سيارة كهربائية', canonical: 'electric car' },
];

/**
 * Spec keys that existed in earlier releases and were replaced by structured
 * tables; the reference seed deletes them when no row uses them.
 */
export const RETIRED_SPEC_KEYS: readonly string[] = [
  'charging.ac_port',
  'charging.dc_port',
  'efficiency.consumption_wh_km',
  'efficiency.fuel_l_100km',
];
