import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {initDb,one} from '../server/db.js';
import {createApp} from '../server/app.js';

test('internal stock requests, optional-supplier receiving and enhanced payroll remain linked',{timeout:90000},async()=>{
 delete process.env.DATABASE_URL;const db=await initDb(':memory:');const app=await createApp(db,{seed:true}),server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const base=`http://127.0.0.1:${(server.address() as any).port}`,cookies:Record<string,string>={};
 const key=()=>randomUUID();async function req(role:string,method:string,path:string,body?:any,status=200){if(!cookies[role]){const login=await fetch(base+'/api/login',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({username:role,password:'Training@2026'})});assert.equal(login.status,200);cookies[role]=login.headers.get('set-cookie')!.split(';')[0]}const response=await fetch(base+'/api'+path,{method,headers:{Origin:base,Cookie:cookies[role],'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),value=await response.json();assert.equal(response.status,status,`${method} ${path}: ${JSON.stringify(value)}`);return value}
 try{
  const stocked=await one(db,'SELECT c.id,c.name,i.stock_section,sum(i.quantity) quantity FROM consumable_catalog c JOIN inventory i ON i.consumable_id=c.id GROUP BY c.id,c.name,i.stock_section HAVING sum(i.quantity)>=1 LIMIT 1');assert.ok(stocked);
  const internal=await req('reception','POST','/stock-requests',{department:'الاستقبال',notes:'صرف يومي',lines:[{consumable_id:stocked.id,quantity:1,stock_section:stocked.stock_section}],idempotency_key:key()},201);let request=(await req('stock','GET','/stock-requests')).find((x:any)=>x.id===internal.id);assert.ok(Number(request.lines[0].available_quantity)>=1);const before=Number((await one(db,'SELECT sum(quantity) q FROM inventory WHERE consumable_id=$1 AND stock_section=$2',[stocked.id,stocked.stock_section])).q);request=await req('stock','POST',`/stock-requests/${request.id}/fulfill`,{version:request.version,idempotency_key:key()});assert.equal(request.status,'fulfilled');assert.equal(Number((await one(db,'SELECT sum(quantity) q FROM inventory WHERE consumable_id=$1 AND stock_section=$2',[stocked.id,stocked.stock_section])).q),before-1);
  const shortage=await req('reception','POST','/stock-requests',{department:'الاستقبال',lines:[{consumable_id:stocked.id,quantity:999999,stock_section:'supplies'}],idempotency_key:key()},201);request=(await req('stock','GET','/stock-requests')).find((x:any)=>x.id===shortage.id);const converted=await req('stock','POST',`/stock-requests/${request.id}/convert-to-purchase`,{version:request.version,lines:[{line_id:request.lines[0].id,quantity:2}],notes:'شراء من السوق',idempotency_key:key()},201);assert.equal(converted.status,'pending');assert.equal(converted.supplier,null);
  let order=await req('purchasing','POST',`/purchase-orders/${converted.id}/approve`,{version:converted.version,approval_note:'شراء مباشر بدون مورد',idempotency_key:key()});assert.equal(order.supplier,null);order=(await req('accountant','GET','/purchase-orders')).find((x:any)=>x.id===converted.id);
  order=await req('accountant','POST',`/purchase-orders/${order.id}/review-receipt`,{version:order.version,settlement:'paid',method:'cash',money_account_id:'cash',reference:'SHOP-RECEIPT-1',invoice_date:'2025-01-15',review_note:'يوجد فرق مؤقت',lines:[{line_id:order.lines[0].id,quantity:1,unit_cost:2,batch:'',expires_at:'',min_quantity:0,location:''}],idempotency_key:key()});await req('accountant','POST',`/purchase-orders/${order.id}/receive`,{version:order.version,idempotency_key:key()},409);order=(await req('accountant','GET','/purchase-orders')).find((x:any)=>x.id===converted.id);
  order=await req('accountant','POST',`/purchase-orders/${order.id}/review-receipt`,{version:order.version,settlement:'paid',method:'cash',money_account_id:'cash',reference:'SHOP-RECEIPT-1',invoice_date:'2025-01-15',review_note:'مطابق',lines:[{line_id:order.lines[0].id,quantity:2,unit_cost:2,batch:'',expires_at:'',min_quantity:0,location:''}],idempotency_key:key()});order=await req('accountant','POST',`/purchase-orders/${order.id}/receive`,{version:order.version,idempotency_key:key()});assert.equal(order.status,'received');const stored=await one(db,"SELECT * FROM inventory WHERE stock_section='supplies' AND batch='SHOP-RECEIPT-1' ORDER BY id DESC LIMIT 1");assert.equal(Number(stored.quantity),2);assert.equal(stored.expires_at,null);

  const employee=await req('manager','POST','/attendance/employees',{name:'موظف رواتب متكامل',employee_no:'PAY-PLUS-1',device_pin:'PAY-PLUS-1',job_type:'purchasing',department:'المشتريات',phone:'01110000000',whatsapp_phone:'01112223333',monthly_salary:3000,daily_work_hours:8,work_days_per_month:30,fixed_allowance:100,transport_allowance:50,meal_allowance:20,fixed_incentive:200,night_shift_rate:75,fixed_deduction:30,salary_transfer_method:'instapay',salary_transfer_number:'01112223333',idempotency_key:key()},201);assert.equal(employee.whatsapp_phone,'01112223333');
  const shift=await req('manager','POST','/attendance/shifts',{employee_id:employee.id,shift_date:'2025-01-15',start_time:'20:00',end_time:'04:00',idempotency_key:key()},201);await req('manager','POST','/attendance/punches',{employee_id:employee.id,device_pin:employee.device_pin,occurred_at:'2025-01-15T20:00:00+02:00',event:'in',reason:'اختبار',idempotency_key:key()},201);await req('manager','POST','/attendance/punches',{employee_id:employee.id,device_pin:employee.device_pin,occurred_at:'2025-01-16T04:00:00+02:00',event:'out',reason:'اختبار',idempotency_key:key()},201);assert.ok(shift.id);
  await req('manager','POST','/payroll/adjustments',{employee_id:employee.id,month:'2025-01',type:'bonus',amount:125,notes:'مكافأة أداء',idempotency_key:key()},201);const payroll=await req('manager','POST','/payroll/preview',{month:'2025-01',idempotency_key:key()},201),row=payroll.employees.find((x:any)=>x.employee_id===employee.id);assert.equal(row.night_shifts,1);assert.equal(row.night_shift_pay,75);assert.equal(row.fixed_additions,370);assert.equal(row.monthly_additions,125);assert.equal(row.fixed_deduction,30);assert.equal(row.net_salary,3540);assert.equal(row.salary_transfer_number,'01112223333');const nurseAttendance=await req('nurse','GET','/attendance');assert.equal('salary_transfer_number' in (nurseAttendance.employees[0]||{}),false);
 }finally{await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));await db.close()}
});
