import { useEffect, useState } from 'react';
import { CheckCircle2, PackageCheck, PackagePlus, RefreshCw, ShoppingCart, XCircle } from 'lucide-react';
import { api, Badge, date, field, fmt, money, Section, Table, type FormSpec, type Row } from './shared';
import { useLanguage } from './i18n';

export default function PurchaseOrders({can,openForm,revision}:{can:(p:string)=>boolean;openForm:(f:FormSpec)=>void;revision:number}){
  const en=useLanguage()==='en',tr=(ar:string,eng:string)=>en?eng:ar;
  const [orders,setOrders]=useState<Row[]>([]),[stockRequests,setStockRequests]=useState<Row[]>([]),[catalog,setCatalog]=useState<Row[]>([]),[accounts,setAccounts]=useState<Row[]>([]),[suppliers,setSuppliers]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;setLoading(true);Promise.all([
    api('/purchase-orders'),api('/stock-requests'),api('/purchase-orders/catalog'),can('billing.write')?api('/treasury'):Promise.resolve({accounts:[]}),can('purchase.approve')?api('/accounting/suppliers'):Promise.resolve([])
  ]).then(([o,r,c,t,s])=>{if(active){setOrders(o);setStockRequests(r);setCatalog(c);setAccounts(t.accounts||[]);setSuppliers(s||[]);setError('')}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[revision,en]);
  const options=catalog.map(c=>({value:c.id,label:`${c.name} · ${c.unit} · ${c.sku}`}));
  const sections=[{value:'general_stock',label:tr('المخزن العام','General stock')},{value:'medical_consumables',label:tr('المستهلكات الطبية','Medical consumables')},{value:'supplies',label:tr('المستلزمات','Supplies')}],sectionName=(value:string)=>sections.find(x=>x.value===value)?.label||value;
  const create=()=>openForm({
    title:tr('طلب شراء مستهلكات أو مستلزمات','Request consumables or supplies'),
    note:tr('الاستقبال يحدد الأصناف والكميات فقط. الأسعار والحسابات المالية لا تظهر في هذه الخطوة.','Reception selects items and quantities only. Prices and financial accounts are hidden at this step.'),
    fields:[...Array.from({length:5},(_,i)=>[
      field(`item_${i}`,tr(`الصنف ${i+1}`,`Item ${i+1}`),'text',i===0,{options,searchable:true}),
      field(`quantity_${i}`,tr(`الكمية ${i+1}`,`Quantity ${i+1}`),'number',i===0,{min:.001,step:'.001'}),
      field(`section_${i}`,tr(`وجهة الصنف ${i+1}`,`Destination ${i+1}`),'text',i===0,{value:'medical_consumables',options:sections})
    ]).flat(),field('notes',tr('سبب الطلب / ملاحظات','Request reason / notes'),'textarea',false,{wide:true})],
    submit:v=>{
      const lines=Array.from({length:5},(_,i)=>({consumable_id:v[`item_${i}`],quantity:v[`quantity_${i}`],stock_section:v[`section_${i}`]})).filter(x=>x.consumable_id||x.quantity);
      if(lines.some(x=>!x.consumable_id||!x.quantity))throw Error(tr('أكمل الصنف والكمية لكل بند مستخدم.','Complete item and quantity for every used line.'));
      return api('/purchase-orders',{lines,notes:v.notes});
    }
  });
  const createStockRequest=()=>openForm({title:tr('طلب صرف أصناف من المخزن','Request items from stock'),note:tr('يرسل الطلب للمخزن بدون أسعار. موظف المخزن يصرفه من الرصيد أو يحول العجز إلى طلب شراء.','The request goes to stock without prices. Stock fulfills it or converts shortages into a purchase request.'),fields:[field('department',tr('القسم الطالب','Requesting department'),'text',true,{value:tr('الاستقبال','Reception')}),...Array.from({length:5},(_,i)=>[field(`item_${i}`,tr(`الصنف ${i+1}`,`Item ${i+1}`),'text',i===0,{options,searchable:true}),field(`quantity_${i}`,tr(`الكمية ${i+1}`,`Quantity ${i+1}`),'number',i===0,{min:.001,step:'.001'}),field(`section_${i}`,tr(`القسم المخزني ${i+1}`,`Stock section ${i+1}`),'text',i===0,{value:'medical_consumables',options:sections})]).flat(),field('notes',tr('سبب الطلب / ملاحظات','Request reason / notes'),'textarea',false,{wide:true})],submit:v=>{const lines=Array.from({length:5},(_,i)=>({consumable_id:v[`item_${i}`],quantity:v[`quantity_${i}`],stock_section:v[`section_${i}`]})).filter(x=>x.consumable_id||x.quantity);if(lines.some(x=>!x.consumable_id||!x.quantity))throw Error(tr('أكمل الصنف والكمية لكل بند مستخدم.','Complete item and quantity for every used line.'));return api('/stock-requests',{department:v.department,notes:v.notes,lines})}});
  const approve=(order:Row)=>openForm({title:tr('اعتماد طلب الشراء','Approve purchase request'),subtitle:order.order_no,note:tr('الاعتماد لا يخصم أي مبلغ ولا يضيف للمخزن؛ التنفيذ والتوريد خطوة منفصلة.','Approval does not debit funds or add stock; execution and receiving are separate.'),fields:[field('supplier_id',tr('المورد المسجل','Registered supplier'),'text',false,{searchable:true,options:suppliers.map(s=>({value:s.id,label:`${s.code} · ${s.name}`}))}),field('supplier',tr('اسم المورد عند عدم تسجيله','Supplier name when not registered'),'text',false),field('approval_note',tr('ملاحظة الاعتماد','Approval note'),'textarea',false)],sensitive:true,submit:v=>api(`/purchase-orders/${order.id}/approve`,{...v,version:order.version})});
  const reject=(order:Row)=>openForm({title:tr('رفض طلب الشراء','Reject purchase request'),subtitle:order.order_no,fields:[field('reason',tr('سبب الرفض','Rejection reason'),'textarea',true)],sensitive:true,submit:v=>api(`/purchase-orders/${order.id}/reject`,{...v,version:order.version})});
  const review=(order:Row)=>openForm({
    title:tr('مطابقة الفاتورة والاستلام المبدئي','Match invoice and preliminary receipt'),subtitle:`${order.order_no} · ${order.supplier||tr('بدون مورد محدد','No specified supplier')}`,
    note:tr('احفظ بيانات الفاتورة والكميات الفعلية أولًا. لن يضاف رصيد ولن يخصم مبلغ حتى تضغط الاستلام النهائي بعد التأكد من عدم وجود فروق.','Save invoice and actual quantities first. Stock and money remain unchanged until final receipt after all differences are cleared.'),initial:{settlement:order.settlement||'paid',supplier_id:order.supplier_id||'',supplier:order.supplier_id?'':order.supplier||'',due_date:order.due_date?.slice?.(0,10)||'',method:order.payment_method||'cash',money_account_id:order.money_account_id||'',reference:order.reference||'',invoice_date:order.invoice_date?.slice?.(0,10)||new Date().toISOString().slice(0,10),review_note:order.review_note||'',...Object.fromEntries(order.lines.flatMap((line:Row,i:number)=>[[`quantity_${i}`,line.delivered_quantity??line.requested_quantity],[`unit_cost_${i}`,line.delivered_unit_cost??''],[`batch_${i}`,line.delivered_batch??''],[`expires_${i}`,line.delivered_expires_at?.slice?.(0,10)??''],[`minimum_${i}`,line.delivered_min_quantity??0],[`location_${i}`,line.delivered_location??'']]))},
    fields:[
      field('settlement',tr('تسوية المورد','Supplier settlement'),'text',true,{value:'paid',options:[{value:'paid',label:tr('مسدد الآن','Paid now')},{value:'credit',label:tr('آجل على المورد','Supplier credit')}]}),
      field('supplier_id',tr('المورد المسجل — اختياري','Registered supplier — optional'),'text',false,{searchable:true,options:suppliers.map(s=>({value:s.id,label:`${s.code} · ${s.name}`}))}),
      field('supplier',tr('اسم محل أو بائع عادي — اختياري','Shop or seller name — optional'),'text',false),
      field('due_date',tr('تاريخ استحقاق المورد عند الآجل','Supplier due date for credit'),'date',false),
      field('method',tr('طريقة السداد عند الدفع الآن','Payment method when paid'),'text',false,{value:'cash',options:[
        {value:'cash',label:tr('نقدي','Cash')},{value:'card',label:tr('فيزا / بطاقة','Card')},{value:'transfer',label:tr('تحويل بنكي','Bank transfer')},{value:'instapay',label:tr('إنستا باي','InstaPay')},{value:'wallet',label:tr('محفظة إلكترونية','Electronic wallet')}
      ]}),
      field('money_account_id',tr('الحساب الذي سدد الشراء','Paying cash / bank account'),'text',false,{searchable:true,options:accounts.filter(a=>a.active).map(a=>({value:a.id,label:`${a.name}${a.bank_name?' · '+a.bank_name:''} · ${money(a.balance)}`}))}),
      field('reference',tr('رقم الفاتورة أو إيصال الشراء','Invoice or purchase receipt number')),
      field('invoice_date',tr('تاريخ الفاتورة','Invoice date'),'date'),
      field('review_note',tr('ملاحظات المطابقة','Matching notes'),'textarea',false,{wide:true}),
      ...order.lines.flatMap((line:Row,i:number)=>[
        field(`quantity_${i}`,`${line.name_snapshot} — ${tr('كمية الفاتورة', 'Invoice quantity')} (${line.unit_snapshot})`,'number',true,{min:.001,step:'.001',help:`${tr('المطلوب','Ordered')}: ${fmt(line.requested_quantity)} · ${sectionName(line.stock_section)}`}),
        field(`unit_cost_${i}`,`${line.name_snapshot} — ${tr('تكلفة الوحدة','Unit cost')}`,'number',true,{min:0,step:'.01'}),
        field(`batch_${i}`,`${line.name_snapshot} — ${tr('رقم التشغيلة — اختياري','Batch — optional')}`,'text',false),
        field(`expires_${i}`,`${line.name_snapshot} — ${tr('تاريخ الصلاحية — اختياري','Expiry date — optional')}`,'date',false),
        field(`minimum_${i}`,`${line.name_snapshot} — ${tr('حد إعادة الطلب','Reorder threshold')}`,'number',true,{value:0,min:0,step:'.001'})
        ,field(`location_${i}`,`${line.name_snapshot} — ${tr('موقع فرعي — اختياري','Sub-location — optional')}`,'text',false,{help:tr('عند تركه فارغًا يستخدم القسم المخزني المختار في الطلب.','When blank, the selected stock section is used.')})
      ])
    ],sensitive:true,
    preview:v=><div className="purchase-match-preview"><Table headers={[tr('الصنف','Item'),tr('المطلوب','Ordered'),tr('بالفاتورة','In invoice'),tr('الفارق','Difference'),tr('القيمة','Value')]} rows={order.lines.map((line:Row,i:number)=>[line.name_snapshot,fmt(line.requested_quantity),fmt(v[`quantity_${i}`]),<strong className={Number(v[`quantity_${i}`]||0)===Number(line.requested_quantity)?'match-ok':'match-difference'}>{fmt(Number(v[`quantity_${i}`]||0)-Number(line.requested_quantity))}</strong>,money(Number(v[`quantity_${i}`]||0)*Number(v[`unit_cost_${i}`]||0))])}/><div className="info-box">{tr('إجمالي الفاتورة: ','Invoice total: ')}<strong>{money(order.lines.reduce((sum:number,_:Row,i:number)=>sum+Number(v[`quantity_${i}`]||0)*Number(v[`unit_cost_${i}`]||0),0))}</strong></div></div>,
    submit:v=>api(`/purchase-orders/${order.id}/review-receipt`,{version:order.version,settlement:v.settlement,supplier_id:v.supplier_id,supplier:v.supplier,method:v.method,money_account_id:v.money_account_id,due_date:v.due_date,reference:v.reference,invoice_date:v.invoice_date,review_note:v.review_note,lines:order.lines.map((line:Row,i:number)=>({line_id:line.id,quantity:v[`quantity_${i}`],unit_cost:v[`unit_cost_${i}`],batch:v[`batch_${i}`],expires_at:v[`expires_${i}`],min_quantity:v[`minimum_${i}`],location:v[`location_${i}`]}))})
  });
  const finalReceive=(order:Row)=>openForm({title:tr('تأكيد الاستلام النهائي','Confirm final receipt'),subtitle:order.order_no,note:tr('بعد التأكيد ستضاف الأصناف تلقائيًا إلى الأقسام المخزنية المحددة، ويُثبت القيد المالي وتكلفة الشراء.','After confirmation, items are added to their selected stock sections and the purchase journal is posted.'),fields:[],sensitive:true,preview:()=> <Table headers={[tr('الصنف','Item'),tr('القسم','Section'),tr('أمر الشراء','Ordered'),tr('الفاتورة','Invoice'),tr('التكلفة','Cost')]} rows={order.lines.map((line:Row)=>[line.name_snapshot,sectionName(line.stock_section),fmt(line.requested_quantity),fmt(line.delivered_quantity),money(Number(line.delivered_quantity)*Number(line.delivered_unit_cost))])}/>,submit:()=>api(`/purchase-orders/${order.id}/receive`,{version:order.version})});
  const fulfillStock=(request:Row)=>openForm({title:tr('صرف الطلب من المخزن','Fulfill stock request'),subtitle:request.request_no,note:tr('سيتم الصرف من التشغيلات الصالحة بالأقرب انتهاءً وتسجيل حركة المخزون باسم الموظف المنفذ.','Valid batches are issued by earliest expiry and the stock movement records the responsible employee.'),fields:[],sensitive:true,preview:()=> <Table headers={[tr('الصنف','Item'),tr('المطلوب','Requested'),tr('المتاح','Available'),tr('القسم','Section')]} rows={request.lines.map((line:Row)=>[line.name_snapshot,fmt(line.requested_quantity),fmt(line.available_quantity),sectionName(line.stock_section)])}/>,submit:()=>api(`/stock-requests/${request.id}/fulfill`,{version:request.version})});
  const convertToPurchase=(request:Row)=>openForm({title:tr('تحويل العجز إلى طلب شراء','Convert shortage to purchase request'),subtitle:request.request_no,note:tr('سينشأ أمر شراء معلق يصل لمسؤول المشتريات أو الحسابات، بدون مورد وبدون أسعار.','A pending purchase order is created for Purchasing or Accounts, without supplier or prices.'),fields:[...request.lines.flatMap((line:Row,i:number)=>[field(`quantity_${i}`,`${line.name_snapshot} — ${tr('كمية الشراء','Purchase quantity')}`,'number',true,{value:Math.max(0,Number(line.requested_quantity)-Number(line.available_quantity)),min:.001,step:'.001',help:`${tr('المتاح','Available')}: ${fmt(line.available_quantity)}`})]),field('notes',tr('ملاحظات لمسؤول المشتريات','Notes for purchasing'),'textarea',false,{wide:true})],submit:v=>api(`/stock-requests/${request.id}/convert-to-purchase`,{version:request.version,notes:v.notes,lines:request.lines.map((line:Row,i:number)=>({line_id:line.id,quantity:v[`quantity_${i}`]})).filter((x:Row)=>Number(x.quantity)>0)})});
  const rejectStock=(request:Row)=>openForm({title:tr('رفض طلب الصرف','Reject stock request'),subtitle:request.request_no,fields:[field('reason',tr('سبب الرفض','Rejection reason'),'textarea',true)],sensitive:true,submit:v=>api(`/stock-requests/${request.id}/reject`,{version:request.version,reason:v.reason})});
  return <div className="purchase-orders">
    <Section title={tr('طلبات الصرف الداخلية','Internal stock requests')} sub={tr('الاستقبال يطلب بدون أسعار؛ المخزن يصرف من الرصيد أو يحول العجز تلقائيًا إلى أمر شراء.','Reception requests without prices; Stock fulfills from balance or converts shortages into a purchase order.')} action={can('purchase.request')?<button className="button primary small" onClick={createStockRequest}><ShoppingCart size={16}/>{tr('طلب صرف من المخزن','Request from stock')}</button>:undefined}>
      {error&&<div className="error-box">{error}</div>}{loading&&<div className="empty-state"><RefreshCw className="spin"/>{tr('جارٍ التحميل…','Loading…')}</div>}
      {!loading&&<Table headers={[tr('الطلب','Request'),tr('القسم والطالب','Department & requester'),tr('الأصناف','Items'),tr('الحالة','Status'),tr('الإجراء','Action')]} rows={stockRequests.map(request=>[
        <div><strong>{request.request_no}</strong><small>{date(request.requested_at,true)}</small></div>,
        <div>{request.department}<small>{request.requested_by_name}</small></div>,
        <div>{request.lines.map((line:Row)=><span className="purchase-line" key={line.id}>{line.name_snapshot} — {fmt(line.requested_quantity)} {line.unit_snapshot}<small>{sectionName(line.stock_section)} · {tr('متاح','Available')} {fmt(line.available_quantity)}</small></span>)}</div>,
        <div><Badge value={request.status}/>{request.order_no&&<small>{tr('أمر شراء: ','Purchase order: ')}{request.order_no}</small>}{request.rejection_reason&&<small>{request.rejection_reason}</small>}</div>,
        <div className="row-actions">{can('stock.write')&&request.status==='pending'&&<><button className="button primary tiny" onClick={()=>fulfillStock(request)}><PackageCheck size={14}/>{tr('صرف','Fulfill')}</button><button className="button tiny" onClick={()=>convertToPurchase(request)}><ShoppingCart size={14}/>{tr('تحويل لشراء','Convert to purchase')}</button><button className="button danger tiny" onClick={()=>rejectStock(request)}><XCircle size={14}/>{tr('رفض','Reject')}</button></>}</div>
      ])}/>} 
    </Section>
    <Section title={tr('طلبات وأوامر الشراء','Purchase requests and orders')} sub={can('billing.write')?tr('اعتماد ثم مطابقة مستقلة للفاتورة قبل الاستلام النهائي والترحيل المحاسبي.','Approve, match the invoice separately, then confirm final receipt and accounting posting.'):tr('الأمر يظل معلقًا حتى الاعتماد والمراجعة والاستلام. لا تظهر الأسعار للحسابات غير المالية.','The order remains pending through approval, review and receipt. Prices stay hidden from non-financial accounts.')} action={can('purchase.request')&&(can('stock.read')||can('purchase.approve'))?<button className="button primary small" onClick={create}><PackagePlus size={16}/>{tr('أمر شراء جديد','New purchase order')}</button>:undefined}>
      {!loading&&<Table headers={[tr('الطلب','Request'),tr('الأصناف والكميات','Items and quantities'),tr('الحالة','Status'),tr('المسؤولون','People'),...(can('purchase.approve')?[tr('التكلفة','Cost')]:[]),tr('الإجراء','Action')]} rows={orders.map(order=>[
        <div><strong>{order.order_no}</strong><small>{date(order.requested_at,true)}{order.notes?` · ${order.notes}`:''}</small></div>,
        <div>{order.lines.map((line:Row)=><span className="purchase-line" key={line.id}>{line.name_snapshot} — {fmt(line.requested_quantity)} {line.unit_snapshot}<small>{sectionName(line.stock_section)}{order.status==='reviewing'?` · ${tr('بالفاتورة','Invoice')}: ${fmt(line.delivered_quantity)}`:''}</small></span>)}</div>,
        <div><Badge value={order.status}/><small>{order.supplier||tr('بدون مورد محدد','No specified supplier')}</small>{order.reference&&<small>{tr('فاتورة: ','Invoice: ')}{order.reference}</small>}</div>,
        <div>{order.requested_by_name}<small>{order.approved_by_name?`${tr('اعتمد: ','Approved: ')}${order.approved_by_name}`:''}</small><small>{order.reviewed_by_name?`${tr('راجع: ','Reviewed: ')}${order.reviewed_by_name}`:''}</small><small>{order.received_by_name?`${tr('استلم: ','Received: ')}${order.received_by_name}`:''}</small></div>,
        ...(can('purchase.approve')?[order.total_amount==null?'—':money(order.total_amount)]:[]),
        <div className="row-actions">{can('purchase.approve')&&order.status==='pending'&&<><button className="button primary tiny" onClick={()=>approve(order)}><CheckCircle2 size={14}/>{tr('اعتماد','Approve')}</button><button className="button danger tiny" onClick={()=>reject(order)}><XCircle size={14}/>{tr('رفض','Reject')}</button></>}{can('billing.write')&&['approved','reviewing'].includes(order.status)&&<button className="button tiny" onClick={()=>review(order)}><PackageCheck size={14}/>{order.status==='reviewing'?tr('تعديل المطابقة','Edit matching'):tr('مطابقة الفاتورة','Match invoice')}</button>}{can('billing.write')&&order.status==='reviewing'&&<button className="button primary tiny" onClick={()=>finalReceive(order)}><PackagePlus size={14}/>{tr('استلام نهائي','Final receipt')}</button>}</div>
      ])}/>} 
    </Section>
  </div>;
}
